# Code generated by apigen. DO NOT EDIT.

"""Generated client and models for the Baseten Inference API.

Use :class:`ApiClient` for synchronous access or :class:`AsyncApiClient` for
asynchronous access.

Types in this module are generated from the OpenAPI specification and are NOT
covered by any stability or compatibility guarantees. They may change without
notice between versions.
"""

from ._client import ApiClient, AsyncApiClient, ResponseError, ResponseErrorResponse
from ._models import (
    AsyncPredictOutput,
    AsyncPredictRequest,
    AsyncRequestError,
    AsyncRequestStatusResponse,
    AsyncRunRemoteInput,
    AsyncRunRemoteOutput,
    CancelAsyncRequestOutput,
    Code,
    ErrorCode,
    ErrorResponse,
    GetAsyncQueueStatusOutput,
    InferenceRetryConfig,
    PredictInput,
    PredictOutput,
    RunRemoteInput,
    RunRemoteOutput,
    Status,
    WebhookStatus,
)

__all__ = [
    "ApiClient",
    "AsyncApiClient",
    "ResponseError",
    "ResponseErrorResponse",
    "AsyncPredictOutput",
    "AsyncPredictRequest",
    "AsyncRequestError",
    "AsyncRequestStatusResponse",
    "AsyncRunRemoteInput",
    "AsyncRunRemoteOutput",
    "CancelAsyncRequestOutput",
    "Code",
    "ErrorCode",
    "ErrorResponse",
    "GetAsyncQueueStatusOutput",
    "InferenceRetryConfig",
    "PredictInput",
    "PredictOutput",
    "RunRemoteInput",
    "RunRemoteOutput",
    "Status",
    "WebhookStatus",
]
