# Code generated by apigen/clientgen. DO NOT EDIT.

from __future__ import annotations

import urllib.parse
from dataclasses import dataclass
from typing import Any, TypeVar

import httpx
from pydantic import BaseModel

from ._models import (
    AsyncPredictOutput,
    AsyncPredictRequest,
    AsyncRequestStatusResponse,
    AsyncRunRemoteInput,
    AsyncRunRemoteOutput,
    CancelAsyncRequestOutput,
    ErrorResponse,
    GetAsyncQueueStatusOutput,
    PredictInput,
    PredictOutput,
    RunRemoteInput,
    RunRemoteOutput,
)

_T = TypeVar("_T", bound=BaseModel)


@dataclass
class ResponseError(Exception):
    status_code: int
    body: str

    def __str__(self) -> str:
        return f"baseten API error (HTTP {self.status_code}): {self.body}"


@dataclass
class ResponseErrorResponse(Exception):
    status_code: int
    error_response: ErrorResponse

    def __str__(self) -> str:
        return f"baseten API error (HTTP {self.status_code}): {self.error_response.model_dump_json()}"


_ERROR_TYPES: dict[str, tuple[type[BaseModel], type[Exception], str]] = {
    "ErrorResponse": (ErrorResponse, ResponseErrorResponse, "error_response"),
}


@dataclass
class _ApiRequest:
    method: str
    path_fmt: str
    path_args: list[str]
    body: Any
    query: Any
    success_code: int
    error_codes: dict[int, str] | None


class ApiClient:
    """Generated HTTP client for the Baseten API.

    Methods on this client are generated from the OpenAPI specification
    and are NOT covered by any stability or compatibility guarantees.
    They may change without notice between versions.
    """

    def __init__(self, http_client: httpx.Client) -> None:
        """Create a new client. The caller is responsible for closing *http_client*."""
        self._http_client = http_client

    def async_predict(
        self, *, env_name: str, request: AsyncPredictRequest
    ) -> AsyncPredictOutput:
        """Asynchronously call a named environment of a model."""
        return self._do_json(
            AsyncPredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/environments/{}/async_predict",
                path_args=[env_name],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    413: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    def async_predict_deployment(
        self, *, deployment_id: str, request: AsyncPredictRequest
    ) -> AsyncPredictOutput:
        """Asynchronously call a specific deployment of a model."""
        return self._do_json(
            AsyncPredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/deployment/{}/async_predict",
                path_args=[deployment_id],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    413: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    def async_predict_development(
        self, *, request: AsyncPredictRequest
    ) -> AsyncPredictOutput:
        """Asynchronously call the development deployment of a model."""
        return self._do_json(
            AsyncPredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/development/async_predict",
                path_args=[],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    413: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    def async_predict_production(
        self, *, request: AsyncPredictRequest
    ) -> AsyncPredictOutput:
        """Asynchronously call the production environment of a model."""
        return self._do_json(
            AsyncPredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/production/async_predict",
                path_args=[],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    413: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    def async_predict_regional(
        self, *, request: AsyncPredictRequest
    ) -> AsyncPredictOutput:
        """Asynchronously call a regional environment of a model."""
        return self._do_json(
            AsyncPredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/async_predict",
                path_args=[],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    413: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    def async_run_remote(
        self, *, env_name: str, request: AsyncRunRemoteInput
    ) -> AsyncRunRemoteOutput:
        """Asynchronously call a named environment of a chain."""
        return self._do_json(
            AsyncRunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/environments/{}/async_run_remote",
                path_args=[env_name],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    def async_run_remote_deployment(
        self, *, deployment_id: str, request: AsyncRunRemoteInput
    ) -> AsyncRunRemoteOutput:
        """Asynchronously call a specific deployment of a chain."""
        return self._do_json(
            AsyncRunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/deployment/{}/async_run_remote",
                path_args=[deployment_id],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    def async_run_remote_development(
        self, *, request: AsyncRunRemoteInput
    ) -> AsyncRunRemoteOutput:
        """Asynchronously call the development deployment of a chain."""
        return self._do_json(
            AsyncRunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/development/async_run_remote",
                path_args=[],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    def async_run_remote_production(
        self, *, request: AsyncRunRemoteInput
    ) -> AsyncRunRemoteOutput:
        """Asynchronously call the production environment of a chain."""
        return self._do_json(
            AsyncRunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/production/async_run_remote",
                path_args=[],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    def async_run_remote_regional(
        self, *, request: AsyncRunRemoteInput
    ) -> AsyncRunRemoteOutput:
        """Asynchronously call a regional environment of a chain."""
        return self._do_json(
            AsyncRunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/async_run_remote",
                path_args=[],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    def cancel_async_request(self, *, request_id: str) -> CancelAsyncRequestOutput:
        """Cancel a queued async request."""
        return self._do_json(
            CancelAsyncRequestOutput,
            _ApiRequest(
                method="DELETE",
                path_fmt="/async_request/{}",
                path_args=[request_id],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    def get_async_queue_status(self, *, env_name: str) -> GetAsyncQueueStatusOutput:
        """Get async queue status for a named environment."""
        return self._do_json(
            GetAsyncQueueStatusOutput,
            _ApiRequest(
                method="GET",
                path_fmt="/environments/{}/async_queue_status",
                path_args=[env_name],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    def get_async_queue_status_deployment(
        self, *, deployment_id: str
    ) -> GetAsyncQueueStatusOutput:
        """Get async queue status for a specific deployment."""
        return self._do_json(
            GetAsyncQueueStatusOutput,
            _ApiRequest(
                method="GET",
                path_fmt="/deployment/{}/async_queue_status",
                path_args=[deployment_id],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    def get_async_queue_status_development(self) -> GetAsyncQueueStatusOutput:
        """Get async queue status for the development deployment."""
        return self._do_json(
            GetAsyncQueueStatusOutput,
            _ApiRequest(
                method="GET",
                path_fmt="/development/async_queue_status",
                path_args=[],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    def get_async_queue_status_production(self) -> GetAsyncQueueStatusOutput:
        """Get async queue status for the production environment."""
        return self._do_json(
            GetAsyncQueueStatusOutput,
            _ApiRequest(
                method="GET",
                path_fmt="/production/async_queue_status",
                path_args=[],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    def get_async_queue_status_regional(self) -> GetAsyncQueueStatusOutput:
        """Get async queue status for a regional environment."""
        return self._do_json(
            GetAsyncQueueStatusOutput,
            _ApiRequest(
                method="GET",
                path_fmt="/async_queue_status",
                path_args=[],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    def get_async_request_status(
        self, *, request_id: str
    ) -> AsyncRequestStatusResponse:
        """Get the status of an async request."""
        return self._do_json(
            AsyncRequestStatusResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/async_request/{}",
                path_args=[request_id],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    def predict(self, *, env_name: str, request: PredictInput) -> PredictOutput:
        """Call the model deployment associated with a specified environment."""
        return self._do_json(
            PredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/environments/{}/predict",
                path_args=[env_name],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    def predict_deployment(
        self, *, deployment_id: str, request: PredictInput
    ) -> PredictOutput:
        """Call a specific deployment of a model by deployment ID."""
        return self._do_json(
            PredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/deployment/{}/predict",
                path_args=[deployment_id],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    def predict_development(self, *, request: PredictInput) -> PredictOutput:
        """Call the development deployment of a model."""
        return self._do_json(
            PredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/development/predict",
                path_args=[],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    def predict_production(self, *, request: PredictInput) -> PredictOutput:
        """Call the production environment of a model."""
        return self._do_json(
            PredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/production/predict",
                path_args=[],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    def predict_regional(self, *, request: PredictInput) -> PredictOutput:
        """Call a regional environment of a model."""
        return self._do_json(
            PredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/predict",
                path_args=[],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    def run_remote(self, *, env_name: str, request: RunRemoteInput) -> RunRemoteOutput:
        """Call the chain deployment associated with a specified environment."""
        return self._do_json(
            RunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/environments/{}/run_remote",
                path_args=[env_name],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    def run_remote_deployment(
        self, *, deployment_id: str, request: RunRemoteInput
    ) -> RunRemoteOutput:
        """Call a specific chain deployment by deployment ID."""
        return self._do_json(
            RunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/deployment/{}/run_remote",
                path_args=[deployment_id],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    def run_remote_development(self, *, request: RunRemoteInput) -> RunRemoteOutput:
        """Call the development deployment of a chain."""
        return self._do_json(
            RunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/development/run_remote",
                path_args=[],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    def run_remote_production(self, *, request: RunRemoteInput) -> RunRemoteOutput:
        """Call the production environment of a chain."""
        return self._do_json(
            RunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/production/run_remote",
                path_args=[],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    def run_remote_regional(self, *, request: RunRemoteInput) -> RunRemoteOutput:
        """Call a regional environment of a chain."""
        return self._do_json(
            RunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/run_remote",
                path_args=[],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    def wake(self, *, env_name: str) -> None:
        """Wake a named environment of a model."""
        self._do_no_response(
            _ApiRequest(
                method="POST",
                path_fmt="/environments/{}/wake",
                path_args=[env_name],
                body=None,
                query=None,
                success_code=202,
                error_codes={401: "ErrorResponse"},
            )
        )

    def wake_deployment(self, *, deployment_id: str) -> None:
        """Wake a specific deployment of a model by deployment ID."""
        self._do_no_response(
            _ApiRequest(
                method="POST",
                path_fmt="/deployment/{}/wake",
                path_args=[deployment_id],
                body=None,
                query=None,
                success_code=202,
                error_codes={401: "ErrorResponse"},
            )
        )

    def wake_development(self) -> None:
        """Wake the development deployment of a model."""
        self._do_no_response(
            _ApiRequest(
                method="POST",
                path_fmt="/development/wake",
                path_args=[],
                body=None,
                query=None,
                success_code=202,
                error_codes={401: "ErrorResponse"},
            )
        )

    def wake_production(self) -> None:
        """Wake the production environment of a model."""
        self._do_no_response(
            _ApiRequest(
                method="POST",
                path_fmt="/production/wake",
                path_args=[],
                body=None,
                query=None,
                success_code=202,
                error_codes={401: "ErrorResponse"},
            )
        )

    def wake_regional(self) -> None:
        """Wake a regional environment of a model."""
        self._do_no_response(
            _ApiRequest(
                method="POST",
                path_fmt="/wake",
                path_args=[],
                body=None,
                query=None,
                success_code=202,
                error_codes={401: "ErrorResponse"},
            )
        )

    def _do(self, request: _ApiRequest) -> httpx.Response:
        path = request.path_fmt.format(
            *[urllib.parse.quote(a, safe="") for a in request.path_args]
        )
        json_body = None
        if request.body is not None:
            if isinstance(request.body, BaseModel):
                # Only fields the caller set are sent, so unset fields fall
                # back to the server default rather than being reset here.
                # An explicit None is kept, since null can mean "clear".
                json_body = request.body.model_dump(mode="json", exclude_unset=True)
            else:
                json_body = request.body
        params = None
        if request.query is not None:
            if isinstance(request.query, BaseModel):
                # As above, plus dropping None: a null query parameter is
                # meaningless and would otherwise serialize as an empty string.
                params = request.query.model_dump(
                    mode="json", exclude_unset=True, exclude_none=True
                )
            else:
                params = request.query
        response = self._http_client.request(
            request.method, path, json=json_body, params=params
        )
        if response.status_code != request.success_code:
            if request.error_codes and response.status_code in request.error_codes:
                error_name = request.error_codes[response.status_code]
                if error_name in _ERROR_TYPES:
                    model_cls, exc_cls, field_name = _ERROR_TYPES[error_name]
                    try:
                        model = model_cls.model_validate_json(response.content)
                        raise exc_cls(
                            status_code=response.status_code,  # ty: ignore[unknown-argument]
                            **{field_name: model},
                        )
                    except exc_cls:
                        raise
                    except Exception:
                        pass
            raise ResponseError(status_code=response.status_code, body=response.text)
        return response

    def _do_json(self, response_type: type[_T], request: _ApiRequest) -> _T:
        response = self._do(request)
        content_type = response.headers.get("content-type", "")
        if not content_type.startswith("application/json"):
            raise ValueError(
                f"unexpected content type {content_type!r}, expected application/json"
            )
        return response_type.model_validate_json(response.content)

    def _do_no_response(self, request: _ApiRequest) -> None:
        self._do(request)


class AsyncApiClient:
    """Generated HTTP client for the Baseten API.

    Methods on this client are generated from the OpenAPI specification
    and are NOT covered by any stability or compatibility guarantees.
    They may change without notice between versions.
    """

    def __init__(self, http_client: httpx.AsyncClient) -> None:
        """Create a new client. The caller is responsible for closing *http_client*."""
        self._http_client = http_client

    async def async_predict(
        self, *, env_name: str, request: AsyncPredictRequest
    ) -> AsyncPredictOutput:
        """Asynchronously call a named environment of a model."""
        return await self._do_json(
            AsyncPredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/environments/{}/async_predict",
                path_args=[env_name],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    413: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    async def async_predict_deployment(
        self, *, deployment_id: str, request: AsyncPredictRequest
    ) -> AsyncPredictOutput:
        """Asynchronously call a specific deployment of a model."""
        return await self._do_json(
            AsyncPredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/deployment/{}/async_predict",
                path_args=[deployment_id],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    413: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    async def async_predict_development(
        self, *, request: AsyncPredictRequest
    ) -> AsyncPredictOutput:
        """Asynchronously call the development deployment of a model."""
        return await self._do_json(
            AsyncPredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/development/async_predict",
                path_args=[],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    413: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    async def async_predict_production(
        self, *, request: AsyncPredictRequest
    ) -> AsyncPredictOutput:
        """Asynchronously call the production environment of a model."""
        return await self._do_json(
            AsyncPredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/production/async_predict",
                path_args=[],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    413: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    async def async_predict_regional(
        self, *, request: AsyncPredictRequest
    ) -> AsyncPredictOutput:
        """Asynchronously call a regional environment of a model."""
        return await self._do_json(
            AsyncPredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/async_predict",
                path_args=[],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    413: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    async def async_run_remote(
        self, *, env_name: str, request: AsyncRunRemoteInput
    ) -> AsyncRunRemoteOutput:
        """Asynchronously call a named environment of a chain."""
        return await self._do_json(
            AsyncRunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/environments/{}/async_run_remote",
                path_args=[env_name],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    async def async_run_remote_deployment(
        self, *, deployment_id: str, request: AsyncRunRemoteInput
    ) -> AsyncRunRemoteOutput:
        """Asynchronously call a specific deployment of a chain."""
        return await self._do_json(
            AsyncRunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/deployment/{}/async_run_remote",
                path_args=[deployment_id],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    async def async_run_remote_development(
        self, *, request: AsyncRunRemoteInput
    ) -> AsyncRunRemoteOutput:
        """Asynchronously call the development deployment of a chain."""
        return await self._do_json(
            AsyncRunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/development/async_run_remote",
                path_args=[],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    async def async_run_remote_production(
        self, *, request: AsyncRunRemoteInput
    ) -> AsyncRunRemoteOutput:
        """Asynchronously call the production environment of a chain."""
        return await self._do_json(
            AsyncRunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/production/async_run_remote",
                path_args=[],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    async def async_run_remote_regional(
        self, *, request: AsyncRunRemoteInput
    ) -> AsyncRunRemoteOutput:
        """Asynchronously call a regional environment of a chain."""
        return await self._do_json(
            AsyncRunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/async_run_remote",
                path_args=[],
                body=request,
                query=None,
                success_code=201,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    async def cancel_async_request(
        self, *, request_id: str
    ) -> CancelAsyncRequestOutput:
        """Cancel a queued async request."""
        return await self._do_json(
            CancelAsyncRequestOutput,
            _ApiRequest(
                method="DELETE",
                path_fmt="/async_request/{}",
                path_args=[request_id],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    async def get_async_queue_status(
        self, *, env_name: str
    ) -> GetAsyncQueueStatusOutput:
        """Get async queue status for a named environment."""
        return await self._do_json(
            GetAsyncQueueStatusOutput,
            _ApiRequest(
                method="GET",
                path_fmt="/environments/{}/async_queue_status",
                path_args=[env_name],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    async def get_async_queue_status_deployment(
        self, *, deployment_id: str
    ) -> GetAsyncQueueStatusOutput:
        """Get async queue status for a specific deployment."""
        return await self._do_json(
            GetAsyncQueueStatusOutput,
            _ApiRequest(
                method="GET",
                path_fmt="/deployment/{}/async_queue_status",
                path_args=[deployment_id],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    async def get_async_queue_status_development(self) -> GetAsyncQueueStatusOutput:
        """Get async queue status for the development deployment."""
        return await self._do_json(
            GetAsyncQueueStatusOutput,
            _ApiRequest(
                method="GET",
                path_fmt="/development/async_queue_status",
                path_args=[],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    async def get_async_queue_status_production(self) -> GetAsyncQueueStatusOutput:
        """Get async queue status for the production environment."""
        return await self._do_json(
            GetAsyncQueueStatusOutput,
            _ApiRequest(
                method="GET",
                path_fmt="/production/async_queue_status",
                path_args=[],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    async def get_async_queue_status_regional(self) -> GetAsyncQueueStatusOutput:
        """Get async queue status for a regional environment."""
        return await self._do_json(
            GetAsyncQueueStatusOutput,
            _ApiRequest(
                method="GET",
                path_fmt="/async_queue_status",
                path_args=[],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    async def get_async_request_status(
        self, *, request_id: str
    ) -> AsyncRequestStatusResponse:
        """Get the status of an async request."""
        return await self._do_json(
            AsyncRequestStatusResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/async_request/{}",
                path_args=[request_id],
                body=None,
                query=None,
                success_code=200,
                error_codes={401: "ErrorResponse", 429: "ErrorResponse"},
            ),
        )

    async def predict(self, *, env_name: str, request: PredictInput) -> PredictOutput:
        """Call the model deployment associated with a specified environment."""
        return await self._do_json(
            PredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/environments/{}/predict",
                path_args=[env_name],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    async def predict_deployment(
        self, *, deployment_id: str, request: PredictInput
    ) -> PredictOutput:
        """Call a specific deployment of a model by deployment ID."""
        return await self._do_json(
            PredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/deployment/{}/predict",
                path_args=[deployment_id],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    async def predict_development(self, *, request: PredictInput) -> PredictOutput:
        """Call the development deployment of a model."""
        return await self._do_json(
            PredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/development/predict",
                path_args=[],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    async def predict_production(self, *, request: PredictInput) -> PredictOutput:
        """Call the production environment of a model."""
        return await self._do_json(
            PredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/production/predict",
                path_args=[],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    async def predict_regional(self, *, request: PredictInput) -> PredictOutput:
        """Call a regional environment of a model."""
        return await self._do_json(
            PredictOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/predict",
                path_args=[],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    async def run_remote(
        self, *, env_name: str, request: RunRemoteInput
    ) -> RunRemoteOutput:
        """Call the chain deployment associated with a specified environment."""
        return await self._do_json(
            RunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/environments/{}/run_remote",
                path_args=[env_name],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    async def run_remote_deployment(
        self, *, deployment_id: str, request: RunRemoteInput
    ) -> RunRemoteOutput:
        """Call a specific chain deployment by deployment ID."""
        return await self._do_json(
            RunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/deployment/{}/run_remote",
                path_args=[deployment_id],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    async def run_remote_development(
        self, *, request: RunRemoteInput
    ) -> RunRemoteOutput:
        """Call the development deployment of a chain."""
        return await self._do_json(
            RunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/development/run_remote",
                path_args=[],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    async def run_remote_production(
        self, *, request: RunRemoteInput
    ) -> RunRemoteOutput:
        """Call the production environment of a chain."""
        return await self._do_json(
            RunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/production/run_remote",
                path_args=[],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    async def run_remote_regional(self, *, request: RunRemoteInput) -> RunRemoteOutput:
        """Call a regional environment of a chain."""
        return await self._do_json(
            RunRemoteOutput,
            _ApiRequest(
                method="POST",
                path_fmt="/run_remote",
                path_args=[],
                body=request,
                query=None,
                success_code=200,
                error_codes={
                    400: "ErrorResponse",
                    401: "ErrorResponse",
                    429: "ErrorResponse",
                    502: "ErrorResponse",
                    503: "ErrorResponse",
                    504: "ErrorResponse",
                },
            ),
        )

    async def wake(self, *, env_name: str) -> None:
        """Wake a named environment of a model."""
        await self._do_no_response(
            _ApiRequest(
                method="POST",
                path_fmt="/environments/{}/wake",
                path_args=[env_name],
                body=None,
                query=None,
                success_code=202,
                error_codes={401: "ErrorResponse"},
            )
        )

    async def wake_deployment(self, *, deployment_id: str) -> None:
        """Wake a specific deployment of a model by deployment ID."""
        await self._do_no_response(
            _ApiRequest(
                method="POST",
                path_fmt="/deployment/{}/wake",
                path_args=[deployment_id],
                body=None,
                query=None,
                success_code=202,
                error_codes={401: "ErrorResponse"},
            )
        )

    async def wake_development(self) -> None:
        """Wake the development deployment of a model."""
        await self._do_no_response(
            _ApiRequest(
                method="POST",
                path_fmt="/development/wake",
                path_args=[],
                body=None,
                query=None,
                success_code=202,
                error_codes={401: "ErrorResponse"},
            )
        )

    async def wake_production(self) -> None:
        """Wake the production environment of a model."""
        await self._do_no_response(
            _ApiRequest(
                method="POST",
                path_fmt="/production/wake",
                path_args=[],
                body=None,
                query=None,
                success_code=202,
                error_codes={401: "ErrorResponse"},
            )
        )

    async def wake_regional(self) -> None:
        """Wake a regional environment of a model."""
        await self._do_no_response(
            _ApiRequest(
                method="POST",
                path_fmt="/wake",
                path_args=[],
                body=None,
                query=None,
                success_code=202,
                error_codes={401: "ErrorResponse"},
            )
        )

    async def _do(self, request: _ApiRequest) -> httpx.Response:
        path = request.path_fmt.format(
            *[urllib.parse.quote(a, safe="") for a in request.path_args]
        )
        json_body = None
        if request.body is not None:
            if isinstance(request.body, BaseModel):
                # Only fields the caller set are sent, so unset fields fall
                # back to the server default rather than being reset here.
                # An explicit None is kept, since null can mean "clear".
                json_body = request.body.model_dump(mode="json", exclude_unset=True)
            else:
                json_body = request.body
        params = None
        if request.query is not None:
            if isinstance(request.query, BaseModel):
                # As above, plus dropping None: a null query parameter is
                # meaningless and would otherwise serialize as an empty string.
                params = request.query.model_dump(
                    mode="json", exclude_unset=True, exclude_none=True
                )
            else:
                params = request.query
        response = await self._http_client.request(
            request.method, path, json=json_body, params=params
        )
        if response.status_code != request.success_code:
            if request.error_codes and response.status_code in request.error_codes:
                error_name = request.error_codes[response.status_code]
                if error_name in _ERROR_TYPES:
                    model_cls, exc_cls, field_name = _ERROR_TYPES[error_name]
                    try:
                        model = model_cls.model_validate_json(response.content)
                        raise exc_cls(
                            status_code=response.status_code,  # ty: ignore[unknown-argument]
                            **{field_name: model},
                        )
                    except exc_cls:
                        raise
                    except Exception:
                        pass
            raise ResponseError(status_code=response.status_code, body=response.text)
        return response

    async def _do_json(self, response_type: type[_T], request: _ApiRequest) -> _T:
        response = await self._do(request)
        content_type = response.headers.get("content-type", "")
        if not content_type.startswith("application/json"):
            raise ValueError(
                f"unexpected content type {content_type!r}, expected application/json"
            )
        return response_type.model_validate_json(response.content)

    async def _do_no_response(self, request: _ApiRequest) -> None:
        await self._do(request)
