# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations
from typing import Annotated, Any
from pydantic import AnyUrl, BaseModel, Field, RootModel
from enum import Enum


class InferenceRetryConfig(BaseModel):
    max_attempts: Annotated[
        int, Field(description="Number of predict request attempts.", ge=1, le=10)
    ] = 3
    initial_delay_ms: Annotated[
        int,
        Field(
            description="Minimum time between retries in milliseconds.", ge=0, le=10000
        ),
    ] = 1000
    max_delay_ms: Annotated[
        int,
        Field(
            description="Maximum time between retries in milliseconds.", ge=0, le=60000
        ),
    ] = 5000


class Status(Enum):
    QUEUED = "QUEUED"
    IN_PROGRESS = "IN_PROGRESS"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    CANCELED = "CANCELED"
    WEBHOOK_FAILED = "WEBHOOK_FAILED"


class WebhookStatus(Enum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"
    NO_WEBHOOK_PROVIDED = "NO_WEBHOOK_PROVIDED"


class Code(Enum):
    MODEL_PREDICT_ERROR = "MODEL_PREDICT_ERROR"
    MODEL_PREDICT_TIMEOUT = "MODEL_PREDICT_TIMEOUT"
    MODEL_NOT_READY = "MODEL_NOT_READY"
    MODEL_DOES_NOT_EXIST = "MODEL_DOES_NOT_EXIST"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    MODEL_INVALID_INPUT = "MODEL_INVALID_INPUT"
    ASYNC_REQUEST_NOT_SUPPORTED = "ASYNC_REQUEST_NOT_SUPPORTED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


class AsyncRequestError(BaseModel):
    code: Annotated[Code, Field(description="The type of error that occurred.")]
    message: Annotated[str, Field(description="Details of the error.")]


class ErrorCode(Enum):
    timeout = "timeout"
    client_error = "client_error"
    model_unavailable = "model_unavailable"
    model_not_ready = "model_not_ready"
    model_does_not_exist = "model_does_not_exist"
    rate_limited = "rate_limited"
    payload_too_large = "payload_too_large"
    unauthorized = "unauthorized"
    application_error = "application_error"
    internal_baseten_error = "internal_baseten_error"


class ErrorResponse(BaseModel):
    error: Annotated[str | None, Field(description="Human-readable error message.")] = (
        None
    )
    error_code: Annotated[
        ErrorCode | None, Field(description="Machine-readable error code.")
    ] = None
    detail: Annotated[
        str | None, Field(description="Additional error details, if available.")
    ] = None


class PredictOutput(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class RunRemoteOutput(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class AsyncPredictOutput(BaseModel):
    request_id: Annotated[str, Field(description="The ID of the async request.")]


class AsyncRunRemoteOutput(BaseModel):
    request_id: Annotated[str, Field(description="The ID of the async request.")]


class CancelAsyncRequestOutput(BaseModel):
    request_id: Annotated[str, Field(description="The ID of the async request.")]
    canceled: Annotated[bool, Field(description="Whether the request was canceled.")]
    message: Annotated[
        str,
        Field(description="Additional details about whether the request was canceled."),
    ]


class GetAsyncQueueStatusOutput(BaseModel):
    model_id: Annotated[str, Field(description="The ID of the model.")]
    deployment_id: Annotated[str, Field(description="The ID of the deployment.")]
    num_queued_requests: Annotated[
        int,
        Field(description="Number of requests with QUEUED status awaiting processing."),
    ]
    num_in_progress_requests: Annotated[
        int,
        Field(description="Number of requests currently being processed by the model."),
    ]


class PredictInput(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class RunRemoteInput(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class AsyncRunRemoteInput(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class AsyncPredictRequest(BaseModel):
    model_input: Annotated[
        dict[str, Any], Field(description="JSON-serializable model input.")
    ]
    webhook_endpoint: Annotated[
        AnyUrl | None,
        Field(
            description="HTTPS URL to receive the prediction result via webhook. Both HTTP/2 and HTTP/1.1 are supported. If omitted, the model must save outputs so they can be accessed later."
        ),
    ] = None
    priority: Annotated[
        int,
        Field(
            description="Priority of the request. Lower values are higher priority.",
            ge=0,
            le=2,
        ),
    ] = 0
    max_time_in_queue_seconds: Annotated[
        int,
        Field(
            description="Maximum time in seconds a request will spend in the queue before expiring. Must be between 10 seconds and 72 hours.",
            ge=10,
            le=259200,
        ),
    ] = 600
    inference_retry_config: InferenceRetryConfig | None = None


class AsyncRequestStatusResponse(BaseModel):
    request_id: Annotated[str, Field(description="The ID of the async request.")]
    model_id: Annotated[
        str | None,
        Field(
            description="The ID of the model that executed the request. Present for model requests."
        ),
    ] = None
    chain_id: Annotated[
        str | None,
        Field(
            description="The ID of the chain that executed the request. Present for chain requests."
        ),
    ] = None
    deployment_id: Annotated[
        str, Field(description="The ID of the deployment that executed the request.")
    ]
    status: Annotated[Status, Field(description="The status of the async request.")]
    webhook_status: Annotated[
        WebhookStatus,
        Field(
            description="The status of sending the prediction result to the provided webhook."
        ),
    ]
    created_at: Annotated[
        str,
        Field(description="The time in UTC at which the async request was created."),
    ]
    status_at: Annotated[
        str,
        Field(
            description="The time in UTC at which the async request's status was last updated."
        ),
    ]
    errors: Annotated[
        list[AsyncRequestError],
        Field(
            default_factory=list,
            description="Errors that occurred while processing the async request. Empty if no errors occurred.",
        ),
    ]
