# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations
from typing import Annotated, Any, Literal
from pydantic import BaseModel, ConfigDict, Field, RootModel
from enum import Enum


class ModelMetadata(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    example_model_input: Annotated[
        Any | None,
        Field(
            description="Sample input that populates the Baseten playground.",
            examples=[{"prompt": "What is the meaning of life?"}],
        ),
    ] = None


class AcceleratorSpec(RootModel[str | None]):
    root: str | None


class AutoscalingMetric(BaseModel):
    name: Annotated[str, Field(title="Name")]
    target: Annotated[float, Field(title="Target")]


class CheckpointSource(Enum):
    HF = "HF"
    GCS = "GCS"
    S3 = "S3"
    AZURE = "AZURE"
    LOCAL = "LOCAL"
    REMOTE_URL = "REMOTE_URL"
    BASETEN_TRAINING = "BASETEN_TRAINING"


class DockerAuthType(Enum):
    GCP_SERVICE_ACCOUNT_JSON = "GCP_SERVICE_ACCOUNT_JSON"
    AWS_IAM = "AWS_IAM"
    AWS_OIDC = "AWS_OIDC"
    GCP_OIDC = "GCP_OIDC"
    REGISTRY_SECRET = "REGISTRY_SECRET"


class DockerServer(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    start_command: Annotated[
        str | None,
        Field(
            description="The command to start the server. Required when no_build is not true.",
            title="Start Command",
        ),
    ] = None
    server_port: Annotated[
        int,
        Field(
            description="The port where the server runs. Port 8080 is reserved by Baseten's internal reverse proxy and cannot be used.",
            title="Server Port",
        ),
    ]
    predict_endpoint: Annotated[
        str,
        Field(
            description="The endpoint for inference requests. This is mapped to Baseten's /predict route.",
            title="Predict Endpoint",
        ),
    ]
    readiness_endpoint: Annotated[
        str,
        Field(
            description="The endpoint for readiness probes. Determines when the container can accept traffic.",
            title="Readiness Endpoint",
        ),
    ]
    liveness_endpoint: Annotated[
        str,
        Field(
            description="The endpoint for liveness probes. Determines if the container needs to be restarted.",
            title="Liveness Endpoint",
        ),
    ]
    run_as_user_id: Annotated[
        int | None,
        Field(
            description="The Linux UID to run the server process as inside the container. Use this when your base image expects a specific non-root user (for example, NVIDIA NIM containers).",
            title="Run As User Id",
        ),
    ] = None
    no_build: Annotated[
        bool | None,
        Field(
            description="Skip the build step and deploy the base image as-is. Baseten copies the image to its container registry without running docker build or modifying the image in any way.",
            title="No Build",
        ),
    ] = None


class ExternalDataItem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    url: Annotated[
        str,
        Field(
            description="URL to download the data from. Currently only files are allowed.",
            min_length=1,
            title="Url",
        ),
    ]
    local_data_path: Annotated[
        str,
        Field(
            description="Path relative to the data directory where the remote file will be downloaded.",
            min_length=1,
            title="Local Data Path",
        ),
    ]
    backend: Annotated[
        str | None,
        Field(
            description="Download backend to use. Defaults to 'http_public'.",
            title="Backend",
        ),
    ] = "http_public"
    name: Annotated[
        str | None,
        Field(
            description="Optional name for the download. Path relative to data directory.",
            title="Name",
        ),
    ] = None


class GRPCOptions(BaseModel):
    kind: Annotated[Literal["grpc"], Field(title="Kind")] = "grpc"


class HTTPOptions(BaseModel):
    kind: Annotated[Literal["http"], Field(title="Kind")] = "http"


class HealthChecks(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    restart_check_delay_seconds: Annotated[
        int | None,
        Field(
            description="The delay in seconds before starting restart checks. Defaults to platform-determined value when not set.",
            title="Restart Check Delay Seconds",
        ),
    ] = None
    restart_threshold_seconds: Annotated[
        int | None,
        Field(
            description="The time in seconds after which an unhealthy instance is restarted. Defaults to platform-determined value when not set.",
            title="Restart Threshold Seconds",
        ),
    ] = None
    stop_traffic_threshold_seconds: Annotated[
        int | None,
        Field(
            description="The time in seconds after which traffic is stopped to an unhealthy instance. Defaults to platform-determined value when not set.",
            title="Stop Traffic Threshold Seconds",
        ),
    ] = None
    startup_threshold_seconds: Annotated[
        int | None,
        Field(
            description="The time in seconds to wait for a model to start before marking it as unhealthy. Defaults to platform-determined value when not set.",
            title="Startup Threshold Seconds",
        ),
    ] = None


class VolumeFolder(RootModel[str]):
    root: Annotated[str | None, Field(min_length=1, title="Volume Folder")] = None


class ModelRepoSourceKind(Enum):
    hf = "hf"
    gcs = "gcs"
    s3 = "s3"
    azure = "azure"


class ModelServer(Enum):
    TrussServer = "TrussServer"
    TRT_LLM = "TRT_LLM"


class RemoteSSH(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: Annotated[
        bool | None,
        Field(
            description="If true, enables SSH access to running model instances.",
            title="Enabled",
        ),
    ] = False


class NodeCount(RootModel[int]):
    root: Annotated[
        int | None,
        Field(
            description="Number of nodes for multi-node deployments.",
            ge=1,
            title="Node Count",
        ),
    ] = None


class Resources(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    cpu: Annotated[
        str | None,
        Field(
            description="CPU resources needed, expressed as either a raw number or millicpus. For example, 500m is half of a CPU core.",
            examples=["1", "500m", "4"],
            title="Cpu",
        ),
    ] = "1"
    memory: Annotated[
        str | None,
        Field(
            description="CPU RAM needed, expressed as a number with units. Units include Gi (Gibibytes), G (Gigabytes), Mi (Mebibytes), and M (Megabytes).",
            examples=["2Gi", "512Mi"],
            title="Memory",
        ),
    ] = "2Gi"
    accelerator: Annotated[
        AcceleratorSpec | None,
        Field(
            description="The GPU type for your instance. To request multiple GPUs, use the ':' operator (e.g. L4:4).",
            examples=["A100", "T4:2", "H100:8"],
        ),
    ] = None
    instance_type: Annotated[
        str | None,
        Field(
            description="The full SKU name for the instance type. When specified, cpu, memory, and accelerator fields are ignored.",
            examples=["L4:4x16"],
            title="Instance Type",
        ),
    ] = None
    node_count: Annotated[
        NodeCount | None,
        Field(
            description="Number of nodes for multi-node deployments.",
            title="Node Count",
        ),
    ] = None


class MaxSeqLen(RootModel[int]):
    root: Annotated[int | None, Field(ge=1, le=1048576, title="Max Seq Len")] = None


class TRTLLMRuntimeConfigurationV2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    max_seq_len: Annotated[MaxSeqLen | None, Field(title="Max Seq Len")] = None
    max_batch_size: Annotated[
        int | None, Field(ge=1, le=2048, title="Max Batch Size")
    ] = 256
    max_num_tokens: Annotated[
        int | None, Field(gt=64, le=131072, title="Max Num Tokens")
    ] = 8192
    tensor_parallel_size: Annotated[
        int | None, Field(ge=1, title="Tensor Parallel Size")
    ] = 1
    enable_chunked_prefill: Annotated[
        bool | None, Field(title="Enable Chunked Prefill")
    ] = True
    served_model_name: Annotated[str | None, Field(title="Served Model Name")] = None
    patch_kwargs: Annotated[
        dict[str, str | int | float | dict[str, Any] | list[Any] | None] | None,
        Field(title="Patch Kwargs"),
    ] = None


class TrainingArtifactReference(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    training_job_id: Annotated[
        str,
        Field(
            description="The training job id that the artifact reference belongs to.",
            title="Training Job Id",
        ),
    ]
    paths: Annotated[
        list[str] | None,
        Field(
            description="The paths of the files to download which can contain * or ?.",
            title="Paths",
        ),
    ] = None


class VersionsOverrides(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    engine_builder_version: Annotated[
        str | None, Field(title="Engine Builder Version")
    ] = None
    briton_version: Annotated[str | None, Field(title="Briton Version")] = None
    bei_version: Annotated[str | None, Field(title="Bei Version")] = None
    bei_bert_version: Annotated[str | None, Field(title="Bei Bert Version")] = None
    v2_llm_version: Annotated[str | None, Field(title="V2 Llm Version")] = None


class WebsocketOptions(BaseModel):
    kind: Annotated[Literal["websocket"], Field(title="Kind")] = "websocket"
    ping_interval_seconds: Annotated[
        float | None, Field(title="Ping Interval Seconds")
    ] = None
    ping_timeout_seconds: Annotated[
        float | None, Field(title="Ping Timeout Seconds")
    ] = None


class WeightsAuthMethod(Enum):
    CUSTOM_SECRET = "CUSTOM_SECRET"
    AWS_OIDC = "AWS_OIDC"
    GCP_OIDC = "GCP_OIDC"


class ModelSpecDecMode(Enum):
    DRAFT_TOKENS_EXTERNAL = "DRAFT_TOKENS_EXTERNAL"
    LOOKAHEAD_DECODING = "LOOKAHEAD_DECODING"


class NumDraftTokens(RootModel[int]):
    root: Annotated[int | None, Field(ge=1, title="Num Draft Tokens")] = None


class LookaheadWindowsSize(RootModel[int]):
    root: Annotated[int | None, Field(ge=1, title="Lookahead Windows Size")] = None


class LookaheadNgramSize(RootModel[int]):
    root: Annotated[int | None, Field(ge=1, title="Lookahead Ngram Size")] = None


class LookaheadVerificationSetSize(RootModel[int]):
    root: Annotated[
        int | None, Field(ge=1, title="Lookahead Verification Set Size")
    ] = None


class ModelTRTLLMBatchSchedulerPolicy(Enum):
    max_utilization = "max_utilization"
    guaranteed_no_evict = "guaranteed_no_evict"


class NumBuilderGpus(RootModel[int]):
    root: Annotated[int | None, Field(ge=1, title="Num Builder Gpus")] = None


class ModelTRTLLMLoraConfiguration(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    max_lora_rank: Annotated[int | None, Field(title="Max Lora Rank")] = 64
    lora_target_modules: Annotated[
        list[str] | None, Field(title="Lora Target Modules")
    ] = []


class ModelTRTLLMModel(Enum):
    encoder = "encoder"
    encoder_bert = "encoder_bert"
    decoder = "decoder"
    palmyra = "palmyra"
    qwen = "qwen"
    llama = "llama"
    mistral = "mistral"
    deepseek = "deepseek"
    whisper = "whisper"


class ModelTRTLLMPluginConfiguration(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    paged_kv_cache: Annotated[bool | None, Field(title="Paged Kv Cache")] = True
    use_paged_context_fmha: Annotated[
        bool | None, Field(title="Use Paged Context Fmha")
    ] = True
    use_fp8_context_fmha: Annotated[
        bool | None, Field(title="Use Fp8 Context Fmha")
    ] = False


class ModelTRTLLMQuantizationType(Enum):
    no_quant = "no_quant"
    weights_int8 = "weights_int8"
    weights_kv_int8 = "weights_kv_int8"
    weights_int4 = "weights_int4"
    weights_int4_kv_int8 = "weights_int4_kv_int8"
    smooth_quant = "smooth_quant"
    fp8 = "fp8"
    fp8_kv = "fp8_kv"
    fp4 = "fp4"
    fp4_kv = "fp4_kv"
    fp4_mlp_only = "fp4_mlp_only"


class KvCacheHostMemoryBytes(RootModel[int]):
    root: Annotated[int | None, Field(ge=1, title="Kv Cache Host Memory Bytes")] = None


class RequestDefaultMaxTokens(RootModel[int]):
    root: Annotated[int | None, Field(ge=1, title="Request Default Max Tokens")] = None


class WebserverDefaultRoute(Enum):
    field_v1_embeddings = "/v1/embeddings"
    field_rerank = "/rerank"
    field_predict = "/predict"
    field_predict_tokens = "/predict_tokens"


class ModelTRTLLMRuntimeConfiguration(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    kv_cache_free_gpu_mem_fraction: Annotated[
        float | None, Field(title="Kv Cache Free Gpu Mem Fraction")
    ] = 0.9
    kv_cache_host_memory_bytes: Annotated[
        KvCacheHostMemoryBytes | None, Field(title="Kv Cache Host Memory Bytes")
    ] = None
    enable_chunked_context: Annotated[
        bool | None, Field(title="Enable Chunked Context")
    ] = True
    batch_scheduler_policy: ModelTRTLLMBatchSchedulerPolicy | None = (
        ModelTRTLLMBatchSchedulerPolicy.guaranteed_no_evict
    )
    request_default_max_tokens: Annotated[
        RequestDefaultMaxTokens | None, Field(title="Request Default Max Tokens")
    ] = None
    served_model_name: Annotated[str | None, Field(title="Served Model Name")] = None
    total_token_limit: Annotated[int | None, Field(title="Total Token Limit")] = 500000
    webserver_default_route: Annotated[
        WebserverDefaultRoute | None, Field(title="Webserver Default Route")
    ] = None


class ModelTRTQuantizationConfiguration(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    calib_size: Annotated[int | None, Field(title="Calib Size")] = 1024
    calib_dataset: Annotated[str | None, Field(title="Calib Dataset")] = (
        "abisee/cnn_dailymail"
    )
    calib_max_seq_length: Annotated[int | None, Field(title="Calib Max Seq Length")] = (
        1536
    )


class AdditionalAutoscalingConfig(BaseModel):
    metrics: Annotated[
        list[AutoscalingMetric],
        Field(description="List of metric targets for autoscaling.", title="Metrics"),
    ]


class BISLLM(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    config: Annotated[
        dict[str, Any] | None,
        Field(
            description="Configuration options for BIS LLM deployments.", title="Config"
        ),
    ] = None
    version: Annotated[
        str | None,
        Field(
            description="The version of the BIS LLM deployment stack.", title="Version"
        ),
    ] = ""
    additional_autoscaling_config: Annotated[
        AdditionalAutoscalingConfig | None,
        Field(description="Additional autoscaling configuration"),
    ] = None


class Build(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    model_server: ModelServer | None = ModelServer.TrussServer
    arguments: Annotated[dict[str, Any] | None, Field(title="Arguments")] = None
    secret_to_path_mapping: Annotated[
        dict[str, str] | None,
        Field(
            description="Grants access to secrets during the build. Provide a mapping between a secret and a path on the image.",
            title="Secret To Path Mapping",
        ),
    ] = None
    no_cache: Annotated[bool | None, Field(title="No Cache")] = False


class CheckpointList(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    download_folder: Annotated[
        str | None,
        Field(
            description="The folder to download the checkpoints to.",
            examples=["/tmp/training_checkpoints"],
            title="Download Folder",
        ),
    ] = "/tmp/training_checkpoints"
    artifact_references: Annotated[
        list[TrainingArtifactReference] | None, Field(title="Artifact References")
    ] = None
    loops_checkpoint_ids: Annotated[
        list[str] | None,
        Field(
            description="Loops checkpoint IDs to deploy. Mutually exclusive with artifact_references.",
            title="Loops Checkpoint Ids",
        ),
    ] = None


class CheckpointRepository(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    source: CheckpointSource
    repo: Annotated[str, Field(title="Repo")]
    revision: Annotated[str | None, Field(title="Revision")] = None
    runtime_secret_name: Annotated[str | None, Field(title="Runtime Secret Name")] = (
        "hf_access_token"
    )


class DockerAuthSettings(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    aws_oidc_role_arn: Annotated[
        str | None,
        Field(
            description="AWS IAM role ARN for OIDC authentication.",
            title="Aws Oidc Role Arn",
        ),
    ] = None
    aws_oidc_region: Annotated[
        str | None,
        Field(
            description="AWS region for OIDC authentication.", title="Aws Oidc Region"
        ),
    ] = None
    gcp_oidc_service_account: Annotated[
        str | None,
        Field(
            description="GCP service account name for OIDC authentication.",
            title="Gcp Oidc Service Account",
        ),
    ] = None
    gcp_oidc_workload_id_provider: Annotated[
        str | None,
        Field(
            description="GCP workload identity provider for OIDC authentication.",
            title="Gcp Oidc Workload Id Provider",
        ),
    ] = None
    auth_method: DockerAuthType
    registry: Annotated[str | None, Field(title="Registry")] = ""
    secret_name: Annotated[str | None, Field(title="Secret Name")] = None
    aws_access_key_id_secret_name: Annotated[
        str | None, Field(title="Aws Access Key Id Secret Name")
    ] = "aws_access_key_id"
    aws_secret_access_key_secret_name: Annotated[
        str | None, Field(title="Aws Secret Access Key Secret Name")
    ] = "aws_secret_access_key"


class ExternalData(RootModel[list[ExternalDataItem]]):
    root: Annotated[
        list[ExternalDataItem],
        Field(
            description="[Experimental] External data is data that is not contained in the Truss folder.\n\nTypically, this will be data stored remotely. This data is guaranteed to be made\navailable under the data directory of the truss.",
            title="ExternalData",
        ),
    ]


class ModelRepo(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    repo_id: Annotated[str, Field(min_length=1, title="Repo Id")]
    revision: Annotated[str | None, Field(title="Revision")] = ""
    allow_patterns: Annotated[list[str] | None, Field(title="Allow Patterns")] = None
    ignore_patterns: Annotated[list[str] | None, Field(title="Ignore Patterns")] = None
    volume_folder: Annotated[VolumeFolder | None, Field(title="Volume Folder")] = None
    use_volume: Annotated[bool, Field(title="Use Volume")]
    kind: ModelRepoSourceKind | None = ModelRepoSourceKind.hf
    runtime_secret_name: Annotated[str | None, Field(title="Runtime Secret Name")] = (
        "hf_access_token"
    )


class ModelRepoCacheInternal(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    repo_id: Annotated[str, Field(min_length=1, title="Repo Id")]
    revision: Annotated[str | None, Field(title="Revision")] = ""
    allow_patterns: Annotated[list[str] | None, Field(title="Allow Patterns")] = None
    ignore_patterns: Annotated[list[str] | None, Field(title="Ignore Patterns")] = None
    volume_folder: Annotated[VolumeFolder | None, Field(title="Volume Folder")] = None
    use_volume: Annotated[bool | None, Field(title="Use Volume")] = False
    kind: ModelRepoSourceKind | None = ModelRepoSourceKind.hf
    runtime_secret_name: Annotated[str | None, Field(title="Runtime Secret Name")] = (
        "hf_access_token"
    )


class Runtime(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    predict_concurrency: Annotated[
        int | None,
        Field(
            description="The number of concurrent requests that can run in your model's predict method. Increase this if your model supports parallelism.",
            title="Predict Concurrency",
        ),
    ] = 1
    streaming_read_timeout: Annotated[
        int | None,
        Field(
            description="The timeout in seconds for streaming read operations.",
            title="Streaming Read Timeout",
        ),
    ] = 60
    enable_tracing_data: Annotated[
        bool | None,
        Field(
            description="If true, enables trace data export with built-in OTEL instrumentation. May add performance overhead.",
            title="Enable Tracing Data",
        ),
    ] = False
    enable_debug_logs: Annotated[
        bool | None,
        Field(
            description="If true, sets the Truss server log level to DEBUG instead of INFO.",
            title="Enable Debug Logs",
        ),
    ] = False
    transport: Annotated[
        HTTPOptions | WebsocketOptions | GRPCOptions | None,
        Field(
            description="The transport protocol for your model. Supports http (default), websocket, and grpc.",
            discriminator="kind",
            title="Transport",
        ),
    ] = None
    is_websocket_endpoint: Annotated[
        bool | None,
        Field(
            description="DEPRECATED. Do not set manually. Automatically inferred from transport.kind == websocket.",
            title="Is Websocket Endpoint",
        ),
    ] = None
    health_checks: HealthChecks | None = None
    remote_ssh: RemoteSSH | None = None
    truss_server_version_override: Annotated[
        str | None,
        Field(
            description="By default, truss servers are built from the same release as the CLI used to push. This field allows specifying a pinned/specific version instead.",
            title="Truss Server Version Override",
        ),
    ] = None


class WeightsAuth(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    aws_oidc_role_arn: Annotated[
        str | None,
        Field(
            description="AWS IAM role ARN for OIDC authentication.",
            title="Aws Oidc Role Arn",
        ),
    ] = None
    aws_oidc_region: Annotated[
        str | None,
        Field(
            description="AWS region for OIDC authentication.", title="Aws Oidc Region"
        ),
    ] = None
    gcp_oidc_service_account: Annotated[
        str | None,
        Field(
            description="GCP service account name for OIDC authentication.",
            title="Gcp Oidc Service Account",
        ),
    ] = None
    gcp_oidc_workload_id_provider: Annotated[
        str | None,
        Field(
            description="GCP workload identity provider for OIDC authentication.",
            title="Gcp Oidc Workload Id Provider",
        ),
    ] = None
    auth_method: Annotated[
        WeightsAuthMethod,
        Field(
            description="Authentication method for downloading weights from the source."
        ),
    ]
    auth_secret_name: Annotated[
        str | None,
        Field(
            description="Baseten secret name containing credentials for accessing the source.",
            title="Auth Secret Name",
        ),
    ] = None


class WeightsSource(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    source: Annotated[
        str,
        Field(
            description="URI with scheme prefix. Use hf://, s3://, gs://, azure://, r2://, or https://. For HuggingFace, use @revision suffix (e.g., hf://owner/repo@main).",
            min_length=1,
            title="Source",
        ),
    ]
    mount_location: Annotated[
        str,
        Field(
            description="Absolute path where weights will be mounted at runtime.",
            min_length=1,
            title="Mount Location",
        ),
    ]
    auth: Annotated[
        WeightsAuth | None,
        Field(
            description="Authentication configuration for accessing the weights source."
        ),
    ] = None
    auth_secret_name: Annotated[
        str | None,
        Field(
            description="Baseten secret name containing credentials. Can also be specified in auth.auth_secret_name.",
            title="Auth Secret Name",
        ),
    ] = None
    allow_patterns: Annotated[
        list[str] | None,
        Field(
            description="File patterns to include (e.g., ['*.safetensors']).",
            title="Allow Patterns",
        ),
    ] = None
    ignore_patterns: Annotated[
        list[str] | None,
        Field(
            description="File patterns to exclude (e.g., ['*.md']).",
            title="Ignore Patterns",
        ),
    ] = None


class BaseImage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    image: Annotated[
        str | None,
        Field(
            description="The path to the Docker image.",
            examples=["vllm/vllm-openai:v0.7.3", "nvcr.io/nvidia/nemo:23.03"],
            title="Image",
        ),
    ] = ""
    python_executable_path: Annotated[
        str | None,
        Field(
            description="A path to the Python executable on the image.",
            examples=["/usr/bin/python"],
            title="Python Executable Path",
        ),
    ] = ""
    docker_auth: Annotated[
        DockerAuthSettings | None,
        Field(
            description="Authentication configuration for a private Docker registry."
        ),
    ] = None


class CacheInternal(RootModel[list[ModelRepoCacheInternal]]):
    root: Annotated[list[ModelRepoCacheInternal], Field(title="CacheInternal")]


class ModelCache(RootModel[list[ModelRepo]]):
    root: Annotated[list[ModelRepo], Field(title="ModelCache")]


class Weights(RootModel[list[WeightsSource]]):
    root: Annotated[
        list[WeightsSource],
        Field(
            description="List of weights sources for the new weights API.",
            title="Weights",
        ),
    ]


class ModelConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    model_name: Annotated[
        str | None,
        Field(
            description="The name of your model. This is displayed in the model details page in the Baseten UI.",
            title="Model Name",
        ),
    ] = None
    model_metadata: Annotated[
        ModelMetadata | None,
        Field(
            description="A flexible field for additional metadata. The entire config file is available to your model at runtime.",
            title="Model Metadata",
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(description="A description of your model.", title="Description"),
    ] = None
    examples_filename: Annotated[
        str | None,
        Field(
            description="Path to a file containing example model inputs.",
            title="Examples Filename",
        ),
    ] = "examples.yaml"
    data_dir: Annotated[
        str | None,
        Field(description="The folder for data files in your Truss.", title="Data Dir"),
    ] = "data"
    external_data: Annotated[
        ExternalData | None,
        Field(
            description="External data to be downloaded and made available under the data directory at serving time."
        ),
    ] = None
    external_package_dirs: Annotated[
        list[str] | None,
        Field(
            description="Use external_package_dirs to access custom packages located outside your Truss. This lets multiple Trusses share the same package.",
            title="External Package Dirs",
        ),
    ] = None
    python_version: Annotated[
        str | None,
        Field(
            description="The Python version to use.",
            examples=["py313", "py312", "py311", "py310", "py39"],
            title="Python Version",
        ),
    ] = "py313"
    base_image: Annotated[
        BaseImage | None,
        Field(
            description="Use a custom Docker base image instead of the default Truss image."
        ),
    ] = None
    requirements_file: Annotated[
        str | None,
        Field(
            description="Path to a dependency file. Supports requirements.txt, pyproject.toml, and uv.lock. Mutually exclusive with 'requirements'.",
            title="Requirements File",
        ),
    ] = None
    requirements: Annotated[
        list[str] | None,
        Field(
            description="A list of Python dependencies in pip requirements file format. Mutually exclusive with 'requirements_file'.",
            title="Requirements",
        ),
    ] = None
    system_packages: Annotated[
        list[str] | None,
        Field(
            description="System packages that you would typically install using apt on a Debian operating system.",
            examples=[["ffmpeg", "libsm6", "libxext6"]],
            title="System Packages",
        ),
    ] = None
    environment_variables: Annotated[
        dict[str, str] | None,
        Field(
            description="Key-value pairs exposed to the environment that the model executes in. Do not store secret values here.",
            title="Environment Variables",
        ),
    ] = None
    secrets: Annotated[
        dict[str, str | None] | None,
        Field(
            description="Declare secrets your model needs at runtime, such as API keys or access tokens. Use null as a placeholder; store actual values in your organization settings.",
            title="Secrets",
        ),
    ] = None
    resources: Resources | None = None
    runtime: Runtime | None = None
    build: Build | None = None
    build_commands: Annotated[
        list[str] | None,
        Field(
            description="A list of shell commands to run during Docker build. These commands execute after system packages and Python requirements are installed.",
            title="Build Commands",
        ),
    ] = None
    docker_server: Annotated[
        DockerServer | None,
        Field(
            description="Deploy a custom Docker image that has its own HTTP server, without writing a Model class."
        ),
    ] = None
    model_cache: Annotated[
        ModelCache | None,
        Field(
            description="Deprecated. Use 'weights' instead. Bundle model weights into your image at build time."
        ),
    ] = None
    weights: Annotated[
        Weights | None,
        Field(
            description="Configure Baseten Delivery Network (BDN) for model weight delivery with multi-tier caching."
        ),
    ] = None
    trt_llm: Annotated[
        TRTLLMConfiguration | None,
        Field(description="TensorRT-LLM configuration for optimized LLM inference."),
    ] = None
    training_checkpoints: Annotated[
        CheckpointList | None,
        Field(description="Configuration for deploying from training checkpoints."),
    ] = None
    bis_llm: Annotated[
        BISLLM | None,
        Field(
            description="Configuration options for BIS LLM deployments. This field may change in the future."
        ),
    ] = None
    input_type: Annotated[str | None, Field(title="Input Type")] = "Any"
    model_framework: Annotated[str | None, Field(title="Model Framework")] = "custom"
    model_type: Annotated[str | None, Field(title="Model Type")] = "Model"
    model_module_dir: Annotated[
        str | None,
        Field(
            description="The folder containing your model class.",
            title="Model Module Dir",
        ),
    ] = "model"
    model_class_filename: Annotated[str | None, Field(title="Model Class Filename")] = (
        "model.py"
    )
    model_class_name: Annotated[
        str | None,
        Field(
            description="The name of the class that defines your Truss model. This class must implement at least a predict method.",
            title="Model Class Name",
        ),
    ] = "Model"
    bundled_packages_dir: Annotated[
        str | None,
        Field(
            description="The folder for custom packages in your Truss.",
            title="Bundled Packages Dir",
        ),
    ] = "packages"
    use_local_src: Annotated[bool | None, Field(title="Use Local Src")] = False
    cache_internal: CacheInternal | None = None
    live_reload: Annotated[
        bool | None,
        Field(
            description="If true, changes to your model code are automatically reloaded without restarting the server.",
            title="Live Reload",
        ),
    ] = False
    apply_library_patches: Annotated[
        bool | None,
        Field(
            description="Whether to apply library patches for improved compatibility.",
            title="Apply Library Patches",
        ),
    ] = True
    spec_version: Annotated[str | None, Field(title="Spec Version")] = "2.0"


class TRTLLMConfigurationV1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    build: ModelTRTLLMBuildConfiguration
    inference_stack: Annotated[Literal["v1"], Field(title="Inference Stack")] = "v1"
    runtime: Annotated[
        ModelTRTLLMRuntimeConfiguration | None,
        Field(
            default_factory=lambda: ModelTRTLLMRuntimeConfiguration.model_validate(
                {
                    "kv_cache_free_gpu_mem_fraction": 0.9,
                    "kv_cache_host_memory_bytes": None,
                    "enable_chunked_context": True,
                    "batch_scheduler_policy": "guaranteed_no_evict",
                    "request_default_max_tokens": None,
                    "served_model_name": None,
                    "total_token_limit": 500000,
                    "webserver_default_route": None,
                }
            )
        ),
    ]
    version_overrides: Annotated[
        VersionsOverrides | None,
        Field(
            default_factory=lambda: VersionsOverrides.model_validate(
                {
                    "engine_builder_version": None,
                    "briton_version": None,
                    "bei_version": None,
                    "bei_bert_version": None,
                    "v2_llm_version": None,
                }
            )
        ),
    ]


class TRTLLMConfigurationV2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    inference_stack: Annotated[Literal["v2"], Field(title="Inference Stack")] = "v2"
    build: ModelTRTLLMBuildConfiguration
    runtime: TRTLLMRuntimeConfigurationV2
    version_overrides: Annotated[
        VersionsOverrides | None,
        Field(
            default_factory=lambda: VersionsOverrides.model_validate(
                {
                    "engine_builder_version": None,
                    "briton_version": None,
                    "bei_version": None,
                    "bei_bert_version": None,
                    "v2_llm_version": None,
                }
            )
        ),
    ]


class ModelSpeculatorConfiguration(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    speculative_decoding_mode: ModelSpecDecMode | None = (
        ModelSpecDecMode.DRAFT_TOKENS_EXTERNAL
    )
    num_draft_tokens: Annotated[
        NumDraftTokens | None, Field(title="Num Draft Tokens")
    ] = None
    checkpoint_repository: CheckpointRepository | None = None
    runtime: Annotated[
        ModelTRTLLMRuntimeConfiguration | None,
        Field(
            default_factory=lambda: ModelTRTLLMRuntimeConfiguration.model_validate(
                {
                    "kv_cache_free_gpu_mem_fraction": 0.9,
                    "kv_cache_host_memory_bytes": None,
                    "enable_chunked_context": True,
                    "batch_scheduler_policy": "guaranteed_no_evict",
                    "request_default_max_tokens": None,
                    "served_model_name": None,
                    "total_token_limit": 500000,
                    "webserver_default_route": None,
                }
            )
        ),
    ]
    build: ModelTRTLLMBuildConfiguration | None = None
    lookahead_windows_size: Annotated[
        LookaheadWindowsSize | None, Field(title="Lookahead Windows Size")
    ] = None
    lookahead_ngram_size: Annotated[
        LookaheadNgramSize | None, Field(title="Lookahead Ngram Size")
    ] = None
    lookahead_verification_set_size: Annotated[
        LookaheadVerificationSetSize | None,
        Field(title="Lookahead Verification Set Size"),
    ] = None
    enable_b10_lookahead: Annotated[
        bool | None, Field(title="Enable B10 Lookahead")
    ] = False


class ModelTRTLLMBuildConfiguration(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    base_model: ModelTRTLLMModel | None = ModelTRTLLMModel.decoder
    max_seq_len: Annotated[MaxSeqLen | None, Field(title="Max Seq Len")] = None
    max_batch_size: Annotated[
        int | None, Field(ge=1, le=2048, title="Max Batch Size")
    ] = 256
    max_num_tokens: Annotated[
        int | None, Field(gt=64, le=1048576, title="Max Num Tokens")
    ] = 8192
    max_beam_width: Annotated[int | None, Field(ge=1, le=1, title="Max Beam Width")] = 1
    max_prompt_embedding_table_size: Annotated[
        int | None, Field(title="Max Prompt Embedding Table Size")
    ] = 0
    checkpoint_repository: CheckpointRepository | None = None
    gather_all_token_logits: Annotated[
        bool | None, Field(title="Gather All Token Logits")
    ] = False
    strongly_typed: Annotated[bool | None, Field(title="Strongly Typed")] = False
    quantization_type: ModelTRTLLMQuantizationType | None = (
        ModelTRTLLMQuantizationType.no_quant
    )
    quantization_config: Annotated[
        ModelTRTQuantizationConfiguration | None,
        Field(
            default_factory=lambda: ModelTRTQuantizationConfiguration.model_validate(
                {
                    "calib_size": 1024,
                    "calib_dataset": "abisee/cnn_dailymail",
                    "calib_max_seq_length": 1536,
                }
            )
        ),
    ]
    tensor_parallel_count: Annotated[
        int | None, Field(ge=1, title="Tensor Parallel Count")
    ] = 1
    pipeline_parallel_count: Annotated[
        int | None, Field(title="Pipeline Parallel Count")
    ] = 1
    moe_expert_parallel_option: Annotated[
        int | None, Field(title="Moe Expert Parallel Option")
    ] = -1
    sequence_parallel_count: Annotated[
        int | None, Field(title="Sequence Parallel Count")
    ] = 1
    plugin_configuration: Annotated[
        ModelTRTLLMPluginConfiguration | None,
        Field(
            default_factory=lambda: ModelTRTLLMPluginConfiguration.model_validate(
                {
                    "paged_kv_cache": True,
                    "use_paged_context_fmha": True,
                    "use_fp8_context_fmha": False,
                }
            )
        ),
    ]
    num_builder_gpus: Annotated[
        NumBuilderGpus | None, Field(title="Num Builder Gpus")
    ] = None
    speculator: ModelSpeculatorConfiguration | None = None
    lora_adapters: Annotated[
        dict[
            Annotated[str, Field(pattern=r"^[a-zA-Z0-9_\-\.:]+$")], CheckpointRepository
        ]
        | None,
        Field(title="Lora Adapters"),
    ] = None
    lora_configuration: ModelTRTLLMLoraConfiguration | None = None
    skip_build_result: Annotated[bool | None, Field(title="Skip Build Result")] = False


class TRTLLMConfiguration(RootModel[TRTLLMConfigurationV1 | TRTLLMConfigurationV2]):
    root: Annotated[
        TRTLLMConfigurationV1 | TRTLLMConfigurationV2,
        Field(title="TRTLLMConfiguration"),
    ]


ModelConfig.model_rebuild()
TRTLLMConfigurationV1.model_rebuild()
TRTLLMConfigurationV2.model_rebuild()
ModelSpeculatorConfiguration.model_rebuild()
