# Code generated by apigen/clientgen. DO NOT EDIT.

from __future__ import annotations

import contextlib
import urllib.parse
from collections.abc import Mapping
from dataclasses import dataclass
from typing import IO, Any, Literal, TypeVar, cast

import httpx
from pydantic import BaseModel, ValidationError

from ._models import (
    ApplyEditRequest,
    ApplyEditResponse,
    ContentSearchResponse,
    DeleteFilesystemParams,
    DeleteFilesystemTreeParams,
    DeleteNetworkProcessMonitorResponse,
    DriveListResponse,
    DriveMountRequest,
    DriveMountResponse,
    DriveUnmountResponse,
    ErrorResponse,
    ExportOptions,
    ExportProgress,
    ExportResult,
    FileRequest,
    FindResponse,
    FuzzySearchResponse,
    GetCodegenRerankingParams,
    GetFilesystemContentSearchParams,
    GetFilesystemFindParams,
    GetFilesystemParams,
    GetFilesystemResponse,
    GetFilesystemSearchParams,
    GetFilesystemTreeResponse,
    GetNetworkProcessPortsResponse,
    GetProcessResponse,
    GetWatchFilesystemParams,
    HandlerReloadResponse,
    HealthResponse,
    MultipartCompleteRequest,
    MultipartInitiateRequest,
    MultipartInitiateResponse,
    MultipartListPartsResponse,
    MultipartListUploadsResponse,
    MultipartUploadPartResponse,
    PortMonitorRequest,
    PostNetworkProcessMonitorResponse,
    ProcessLogs,
    ProcessRequest,
    ProcessResponse,
    PutFilesystemMultipartPartParams,
    PutFilesystemTreeResponse,
    QuiesceStatus,
    RerankingResponse,
    SuccessResponse,
    TreeRequest,
    TunnelConfigRequest,
    UpgradeRequest,
)

_T = TypeVar("_T", bound=BaseModel)


@dataclass
class ResponseError(Exception):
    status_code: int
    body: str

    def __str__(self) -> str:
        return f"baseten API error (HTTP {self.status_code}): {self.body}"


@dataclass
class ResponseErrorResponse(Exception):
    status_code: int
    error_response: ErrorResponse

    def __str__(self) -> str:
        return f"baseten API error (HTTP {self.status_code}): {self.error_response.model_dump_json()}"


_ERROR_TYPES: dict[str, tuple[type[BaseModel], type[Exception], str]] = {
    "ErrorResponse": (ErrorResponse, ResponseErrorResponse, "error_response"),
}


@dataclass
class _ApiRequest:
    method: str
    path_fmt: str
    path_args: list[str]
    body: Any
    query: Any
    success_codes: list[int]
    error_codes: dict[int, str] | None
    body_content_type: str | None = None
    accept: str | None = None


class ApiClient:
    """Generated HTTP client for the Baseten API.

    Methods on this client are generated from the OpenAPI specification
    and are NOT covered by any stability or compatibility guarantees.
    They may change without notice between versions.
    """

    def __init__(self, http_client: httpx.Client) -> None:
        """Create a new client. The caller is responsible for closing *http_client*."""
        self._http_client = http_client

    def delete_drives_mount(self, *, mount_path: str) -> DriveUnmountResponse:
        """Detach a drive from a local path"""
        return self._do_json(
            DriveUnmountResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/drives/mount/{}",
                path_args=[mount_path],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={400: "ErrorResponse", 500: "ErrorResponse"},
            ),
        )

    def delete_filesystem(
        self, *, path: str, params: DeleteFilesystemParams | None = None
    ) -> SuccessResponse:
        """Delete file or directory"""
        return self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/filesystem/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def delete_filesystem_multipart_abort(self, *, upload_id: str) -> SuccessResponse:
        """Abort multipart upload"""
        return self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/filesystem-multipart/{}/abort",
                path_args=[upload_id],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    404: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def delete_filesystem_tree(
        self, *, path: str, params: DeleteFilesystemTreeParams | None = None
    ) -> SuccessResponse:
        """Delete directory tree"""
        return self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/filesystem/tree/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def delete_network_process_monitor(
        self, *, pid: str
    ) -> DeleteNetworkProcessMonitorResponse:
        """Stop monitoring ports for a process"""
        return self._do_json(
            DeleteNetworkProcessMonitorResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/network/process/{}/monitor",
                path_args=[pid],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def delete_network_tunnel(self) -> SuccessResponse:
        """Disconnect tunnel"""
        return self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/network/tunnel",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={400: "ErrorResponse", 500: "ErrorResponse"},
            ),
        )

    def delete_process(self, *, identifier: str) -> SuccessResponse:
        """Stop a process"""
        return self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/process/{}",
                path_args=[identifier],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def delete_process_kill(self, *, identifier: str) -> SuccessResponse:
        """Kill a process"""
        return self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/process/{}/kill",
                path_args=[identifier],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def delete_process_stdin(self, *, identifier: str) -> SuccessResponse:
        """Close a process's stdin"""
        return self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/process/{}/stdin",
                path_args=[identifier],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={404: "ErrorResponse", 409: "ErrorResponse"},
            ),
        )

    def get_archive_status(self) -> QuiesceStatus:
        """Get the archive status"""
        return self._do_json(
            QuiesceStatus,
            _ApiRequest(
                method="GET",
                path_fmt="/archive/status",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes=None,
            ),
        )

    def get_codegen_reranking(
        self, *, path: str, params: GetCodegenRerankingParams
    ) -> RerankingResponse:
        """Code reranking/semantic search"""
        return self._do_json(
            RerankingResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/codegen/reranking/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    def get_drives_mount(self) -> DriveListResponse:
        """List currently mounted drives"""
        return self._do_json(
            DriveListResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/drives/mount",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={500: "ErrorResponse"},
            ),
        )

    def get_filesystem(
        self, *, path: str, params: GetFilesystemParams | None = None
    ) -> GetFilesystemResponse:
        """Get file or directory information"""
        return self._do_json(
            GetFilesystemResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def get_filesystem_raw(
        self,
        *,
        path: str,
        params: GetFilesystemParams | None = None,
        accept: Literal["application/json", "application/octet-stream"],
    ) -> httpx.Response:
        """Get file or directory information. Returns the response unread, in the requested content type. The caller must close the response."""
        return self._do_raw(
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
                accept=accept,
            )
        )

    def get_filesystem_content_search(
        self, *, path: str, params: GetFilesystemContentSearchParams
    ) -> ContentSearchResponse:
        """Search for text content in files"""
        return self._do_json(
            ContentSearchResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem-content-search/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def get_filesystem_find(
        self, *, path: str, params: GetFilesystemFindParams | None = None
    ) -> FindResponse:
        """Find files and directories"""
        return self._do_json(
            FindResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem-find/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def get_filesystem_multipart(self) -> MultipartListUploadsResponse:
        """List multipart uploads"""
        return self._do_json(
            MultipartListUploadsResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem-multipart",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={500: "ErrorResponse"},
            ),
        )

    def get_filesystem_multipart_parts(
        self, *, upload_id: str
    ) -> MultipartListPartsResponse:
        """List parts"""
        return self._do_json(
            MultipartListPartsResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem-multipart/{}/parts",
                path_args=[upload_id],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    404: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def get_filesystem_search(
        self, *, path: str, params: GetFilesystemSearchParams | None = None
    ) -> FuzzySearchResponse:
        """Fuzzy search for files and directories"""
        return self._do_json(
            FuzzySearchResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem-search/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def get_filesystem_tree(self, *, path: str) -> GetFilesystemTreeResponse:
        """Get directory tree"""
        return self._do_json(
            GetFilesystemTreeResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem/tree/{}",
                path_args=[path],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def get_health(self) -> HealthResponse:
        """Health check"""
        return self._do_json(
            HealthResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/health",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes=None,
            ),
        )

    def get_network_process_ports(self, *, pid: str) -> GetNetworkProcessPortsResponse:
        """Get open ports for a process"""
        return self._do_json(
            GetNetworkProcessPortsResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/network/process/{}/ports",
                path_args=[pid],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def get_process(self) -> GetProcessResponse:
        """List all processes"""
        return self._do_json(
            GetProcessResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/process",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes=None,
            ),
        )

    def get_process_identifier(self, *, identifier: str) -> ProcessResponse:
        """Get process by identifier"""
        return self._do_json(
            ProcessResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/process/{}",
                path_args=[identifier],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={404: "ErrorResponse"},
            ),
        )

    def get_process_logs(self, *, identifier: str) -> ProcessLogs:
        """Get process logs"""
        return self._do_json(
            ProcessLogs,
            _ApiRequest(
                method="GET",
                path_fmt="/process/{}/logs",
                path_args=[identifier],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def get_process_logs_stream(self, *, identifier: str) -> httpx.Response:
        """Stream process logs in real time. Returns the response unread. The caller must close the response."""
        return self._do_raw(
            _ApiRequest(
                method="GET",
                path_fmt="/process/{}/logs/stream",
                path_args=[identifier],
                body=None,
                query=None,
                success_codes=[200],
                error_codes=None,
                accept="text/plain",
            )
        )

    def get_watch_filesystem(
        self, *, path: str, params: GetWatchFilesystemParams | None = None
    ) -> httpx.Response:
        """Stream file modification events in a directory. Returns the response unread. The caller must close the response."""
        return self._do_raw(
            _ApiRequest(
                method="GET",
                path_fmt="/watch/filesystem/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes=None,
                accept="text/plain",
            )
        )

    def post_archive_export(
        self, *, request: ExportOptions
    ) -> ExportResult | ExportProgress:
        """Export the filesystem changes to a presigned URL"""
        return self._do_json_with_status(
            {200: ExportResult, 202: ExportProgress},
            _ApiRequest(
                method="POST",
                path_fmt="/archive/export",
                path_args=[],
                body=request,
                query=None,
                success_codes=[200, 202],
                error_codes={
                    400: "ErrorResponse",
                    409: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def post_archive_resume(self) -> QuiesceStatus:
        """Lift the archive freeze"""
        return self._do_json(
            QuiesceStatus,
            _ApiRequest(
                method="POST",
                path_fmt="/archive/resume",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={409: "ErrorResponse", 500: "ErrorResponse"},
            ),
        )

    def post_drives_mount(self, *, request: DriveMountRequest) -> DriveMountResponse:
        """Attach a drive to a local path"""
        return self._do_json(
            DriveMountResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/drives/mount",
                path_args=[],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    403: "ErrorResponse",
                    409: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def post_environment_reload(self) -> HandlerReloadResponse:
        """Reload environment from guest metadata"""
        return self._do_json(
            HandlerReloadResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/environment/reload",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={404: "ErrorResponse", 500: "ErrorResponse"},
            ),
        )

    def post_filesystem_multipart_complete(
        self, *, upload_id: str, request: MultipartCompleteRequest
    ) -> SuccessResponse:
        """Complete multipart upload"""
        return self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/filesystem-multipart/{}/complete",
                path_args=[upload_id],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    404: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def post_filesystem_multipart_initiate(
        self, *, path: str, request: MultipartInitiateRequest
    ) -> MultipartInitiateResponse:
        """Initiate multipart upload"""
        return self._do_json(
            MultipartInitiateResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/filesystem-multipart/initiate/{}",
                path_args=[path],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={400: "ErrorResponse", 500: "ErrorResponse"},
            ),
        )

    def post_network_process_monitor(
        self, *, pid: str, request: PortMonitorRequest
    ) -> PostNetworkProcessMonitorResponse:
        """Start monitoring ports for a process"""
        return self._do_json(
            PostNetworkProcessMonitorResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/network/process/{}/monitor",
                path_args=[pid],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def post_process(self, *, request: ProcessRequest) -> ProcessResponse:
        """Execute a command"""
        return self._do_json(
            ProcessResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/process",
                path_args=[],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def post_process_raw(
        self,
        *,
        request: ProcessRequest,
        accept: Literal["application/json", "text/event-stream"],
    ) -> httpx.Response:
        """Execute a command. Returns the response unread, in the requested content type. The caller must close the response."""
        return self._do_raw(
            _ApiRequest(
                method="POST",
                path_fmt="/process",
                path_args=[],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
                accept=accept,
            )
        )

    def post_process_stdin(
        self, *, identifier: str, content: bytes | IO[bytes] | str
    ) -> SuccessResponse:
        """Write to a process's stdin"""
        return self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/process/{}/stdin",
                path_args=[identifier],
                body=content,
                query=None,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    409: "ErrorResponse",
                    413: "ErrorResponse",
                    500: "ErrorResponse",
                    503: "ErrorResponse",
                },
                body_content_type="application/octet-stream",
            ),
        )

    def post_upgrade(self, *, request: UpgradeRequest) -> SuccessResponse:
        """Upgrade the sandbox-api"""
        return self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/upgrade",
                path_args=[],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={500: "ErrorResponse"},
            ),
        )

    def put_codegen_fastapply(
        self, *, path: str, request: ApplyEditRequest
    ) -> ApplyEditResponse:
        """Apply code edit"""
        return self._do_json(
            ApplyEditResponse,
            _ApiRequest(
                method="PUT",
                path_fmt="/codegen/fastapply/{}",
                path_args=[path],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    def put_filesystem(self, *, path: str, request: FileRequest) -> SuccessResponse:
        """Create or update a file or directory"""
        return self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="PUT",
                path_fmt="/filesystem/{}",
                path_args=[path],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def put_filesystem_multipart_part(
        self, *, upload_id: str, params: PutFilesystemMultipartPartParams, files: Any
    ) -> MultipartUploadPartResponse:
        """Upload part. *files* is sent as httpx ``files``."""
        return self._do_json(
            MultipartUploadPartResponse,
            _ApiRequest(
                method="PUT",
                path_fmt="/filesystem-multipart/{}/part",
                path_args=[upload_id],
                body=files,
                query=params,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    404: "ErrorResponse",
                    500: "ErrorResponse",
                },
                body_content_type="multipart/form-data",
            ),
        )

    def put_filesystem_tree(
        self, *, path: str, request: TreeRequest
    ) -> PutFilesystemTreeResponse:
        """Create or update directory tree"""
        return self._do_json(
            PutFilesystemTreeResponse,
            _ApiRequest(
                method="PUT",
                path_fmt="/filesystem/tree/{}",
                path_args=[path],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def put_network_tunnel_config(
        self, *, request: TunnelConfigRequest
    ) -> SuccessResponse:
        """Update tunnel configuration"""
        return self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="PUT",
                path_fmt="/network/tunnel/config",
                path_args=[],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def _build_request(self, request: _ApiRequest) -> httpx.Request:
        path = request.path_fmt.format(
            *[urllib.parse.quote(a, safe="") for a in request.path_args]
        )
        json_body = None
        content_body = None
        files_body = None
        headers: dict[str, str] = {}
        if request.accept is not None:
            headers["Accept"] = request.accept
        if request.body is not None:
            if request.body_content_type is None:
                if isinstance(request.body, BaseModel):
                    # Only fields the caller set are sent, so unset fields fall
                    # back to the server default rather than being reset here.
                    # An explicit None is kept, since null can mean "clear".
                    # by_alias: a field renamed for Python (e.g. async_ for
                    # "async") must serialize under its API name.
                    json_body = request.body.model_dump(
                        mode="json", exclude_unset=True, by_alias=True
                    )
                else:
                    json_body = request.body
            elif request.body_content_type == "multipart/form-data":
                # httpx derives the multipart Content-Type, boundary included.
                files_body = request.body
            else:
                headers["Content-Type"] = request.body_content_type
                content_body = request.body
        params = None
        if request.query is not None:
            if isinstance(request.query, BaseModel):
                # As above, plus dropping None: a null query parameter is
                # meaningless and would otherwise serialize as an empty string.
                params = request.query.model_dump(
                    mode="json", exclude_unset=True, exclude_none=True, by_alias=True
                )
            else:
                params = request.query
        return self._http_client.build_request(
            request.method,
            path,
            json=json_body,
            content=content_body,
            files=files_body,
            params=params,
            headers=headers,
        )

    def _do(self, request: _ApiRequest) -> httpx.Response:
        response = self._http_client.send(self._build_request(request))
        if response.status_code not in request.success_codes:
            if request.error_codes and response.status_code in request.error_codes:
                error_name = request.error_codes[response.status_code]
                if error_name in _ERROR_TYPES:
                    model_cls, exc_cls, field_name = _ERROR_TYPES[error_name]
                    # A body that does not match the declared error schema
                    # falls through to the generic ResponseError below.
                    model = None
                    with contextlib.suppress(ValidationError):
                        model = model_cls.model_validate_json(response.content)
                    if model is not None:
                        raise exc_cls(
                            status_code=response.status_code,  # ty: ignore[unknown-argument]
                            **{field_name: model},
                        )
            raise ResponseError(status_code=response.status_code, body=response.text)
        return response

    def _do_raw(self, request: _ApiRequest) -> httpx.Response:
        response = self._http_client.send(self._build_request(request), stream=True)
        if response.status_code not in request.success_codes:
            response.read()
            if request.error_codes and response.status_code in request.error_codes:
                error_name = request.error_codes[response.status_code]
                if error_name in _ERROR_TYPES:
                    model_cls, exc_cls, field_name = _ERROR_TYPES[error_name]
                    # A body that does not match the declared error schema
                    # falls through to the generic ResponseError below.
                    model = None
                    with contextlib.suppress(ValidationError):
                        model = model_cls.model_validate_json(response.content)
                    if model is not None:
                        raise exc_cls(
                            status_code=response.status_code,  # ty: ignore[unknown-argument]
                            **{field_name: model},
                        )
            raise ResponseError(status_code=response.status_code, body=response.text)
        return response

    def _do_json(self, response_type: type[_T], request: _ApiRequest) -> _T:
        response = self._do(request)
        content_type = response.headers.get("content-type", "")
        if not content_type.startswith("application/json"):
            raise ValueError(
                f"unexpected content type {content_type!r}, expected application/json"
            )
        return response_type.model_validate_json(response.content)

    def _do_json_with_status(
        self, response_types: Mapping[int, type[_T]], request: _ApiRequest
    ) -> _T:
        response = self._do(request)
        response_type = response_types.get(response.status_code)
        if response_type is None:
            # A bodyless success code, such as 204 alongside a JSON 200. The
            # call site's return type includes None only when one is declared,
            # so this cast is unreachable otherwise.
            return cast(_T, None)
        content_type = response.headers.get("content-type", "")
        if not content_type.startswith("application/json"):
            raise ValueError(
                f"unexpected content type {content_type!r}, expected application/json"
            )
        return response_type.model_validate_json(response.content)


class AsyncApiClient:
    """Generated HTTP client for the Baseten API.

    Methods on this client are generated from the OpenAPI specification
    and are NOT covered by any stability or compatibility guarantees.
    They may change without notice between versions.
    """

    def __init__(self, http_client: httpx.AsyncClient) -> None:
        """Create a new client. The caller is responsible for closing *http_client*."""
        self._http_client = http_client

    async def delete_drives_mount(self, *, mount_path: str) -> DriveUnmountResponse:
        """Detach a drive from a local path"""
        return await self._do_json(
            DriveUnmountResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/drives/mount/{}",
                path_args=[mount_path],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={400: "ErrorResponse", 500: "ErrorResponse"},
            ),
        )

    async def delete_filesystem(
        self, *, path: str, params: DeleteFilesystemParams | None = None
    ) -> SuccessResponse:
        """Delete file or directory"""
        return await self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/filesystem/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def delete_filesystem_multipart_abort(
        self, *, upload_id: str
    ) -> SuccessResponse:
        """Abort multipart upload"""
        return await self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/filesystem-multipart/{}/abort",
                path_args=[upload_id],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    404: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def delete_filesystem_tree(
        self, *, path: str, params: DeleteFilesystemTreeParams | None = None
    ) -> SuccessResponse:
        """Delete directory tree"""
        return await self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/filesystem/tree/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def delete_network_process_monitor(
        self, *, pid: str
    ) -> DeleteNetworkProcessMonitorResponse:
        """Stop monitoring ports for a process"""
        return await self._do_json(
            DeleteNetworkProcessMonitorResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/network/process/{}/monitor",
                path_args=[pid],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def delete_network_tunnel(self) -> SuccessResponse:
        """Disconnect tunnel"""
        return await self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/network/tunnel",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={400: "ErrorResponse", 500: "ErrorResponse"},
            ),
        )

    async def delete_process(self, *, identifier: str) -> SuccessResponse:
        """Stop a process"""
        return await self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/process/{}",
                path_args=[identifier],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def delete_process_kill(self, *, identifier: str) -> SuccessResponse:
        """Kill a process"""
        return await self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/process/{}/kill",
                path_args=[identifier],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def delete_process_stdin(self, *, identifier: str) -> SuccessResponse:
        """Close a process's stdin"""
        return await self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="DELETE",
                path_fmt="/process/{}/stdin",
                path_args=[identifier],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={404: "ErrorResponse", 409: "ErrorResponse"},
            ),
        )

    async def get_archive_status(self) -> QuiesceStatus:
        """Get the archive status"""
        return await self._do_json(
            QuiesceStatus,
            _ApiRequest(
                method="GET",
                path_fmt="/archive/status",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes=None,
            ),
        )

    async def get_codegen_reranking(
        self, *, path: str, params: GetCodegenRerankingParams
    ) -> RerankingResponse:
        """Code reranking/semantic search"""
        return await self._do_json(
            RerankingResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/codegen/reranking/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    async def get_drives_mount(self) -> DriveListResponse:
        """List currently mounted drives"""
        return await self._do_json(
            DriveListResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/drives/mount",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={500: "ErrorResponse"},
            ),
        )

    async def get_filesystem(
        self, *, path: str, params: GetFilesystemParams | None = None
    ) -> GetFilesystemResponse:
        """Get file or directory information"""
        return await self._do_json(
            GetFilesystemResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def get_filesystem_raw(
        self,
        *,
        path: str,
        params: GetFilesystemParams | None = None,
        accept: Literal["application/json", "application/octet-stream"],
    ) -> httpx.Response:
        """Get file or directory information. Returns the response unread, in the requested content type. The caller must close the response."""
        return await self._do_raw(
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
                accept=accept,
            )
        )

    async def get_filesystem_content_search(
        self, *, path: str, params: GetFilesystemContentSearchParams
    ) -> ContentSearchResponse:
        """Search for text content in files"""
        return await self._do_json(
            ContentSearchResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem-content-search/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def get_filesystem_find(
        self, *, path: str, params: GetFilesystemFindParams | None = None
    ) -> FindResponse:
        """Find files and directories"""
        return await self._do_json(
            FindResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem-find/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def get_filesystem_multipart(self) -> MultipartListUploadsResponse:
        """List multipart uploads"""
        return await self._do_json(
            MultipartListUploadsResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem-multipart",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={500: "ErrorResponse"},
            ),
        )

    async def get_filesystem_multipart_parts(
        self, *, upload_id: str
    ) -> MultipartListPartsResponse:
        """List parts"""
        return await self._do_json(
            MultipartListPartsResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem-multipart/{}/parts",
                path_args=[upload_id],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    404: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def get_filesystem_search(
        self, *, path: str, params: GetFilesystemSearchParams | None = None
    ) -> FuzzySearchResponse:
        """Fuzzy search for files and directories"""
        return await self._do_json(
            FuzzySearchResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem-search/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def get_filesystem_tree(self, *, path: str) -> GetFilesystemTreeResponse:
        """Get directory tree"""
        return await self._do_json(
            GetFilesystemTreeResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/filesystem/tree/{}",
                path_args=[path],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def get_health(self) -> HealthResponse:
        """Health check"""
        return await self._do_json(
            HealthResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/health",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes=None,
            ),
        )

    async def get_network_process_ports(
        self, *, pid: str
    ) -> GetNetworkProcessPortsResponse:
        """Get open ports for a process"""
        return await self._do_json(
            GetNetworkProcessPortsResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/network/process/{}/ports",
                path_args=[pid],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def get_process(self) -> GetProcessResponse:
        """List all processes"""
        return await self._do_json(
            GetProcessResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/process",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes=None,
            ),
        )

    async def get_process_identifier(self, *, identifier: str) -> ProcessResponse:
        """Get process by identifier"""
        return await self._do_json(
            ProcessResponse,
            _ApiRequest(
                method="GET",
                path_fmt="/process/{}",
                path_args=[identifier],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={404: "ErrorResponse"},
            ),
        )

    async def get_process_logs(self, *, identifier: str) -> ProcessLogs:
        """Get process logs"""
        return await self._do_json(
            ProcessLogs,
            _ApiRequest(
                method="GET",
                path_fmt="/process/{}/logs",
                path_args=[identifier],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def get_process_logs_stream(self, *, identifier: str) -> httpx.Response:
        """Stream process logs in real time. Returns the response unread. The caller must close the response."""
        return await self._do_raw(
            _ApiRequest(
                method="GET",
                path_fmt="/process/{}/logs/stream",
                path_args=[identifier],
                body=None,
                query=None,
                success_codes=[200],
                error_codes=None,
                accept="text/plain",
            )
        )

    async def get_watch_filesystem(
        self, *, path: str, params: GetWatchFilesystemParams | None = None
    ) -> httpx.Response:
        """Stream file modification events in a directory. Returns the response unread. The caller must close the response."""
        return await self._do_raw(
            _ApiRequest(
                method="GET",
                path_fmt="/watch/filesystem/{}",
                path_args=[path],
                body=None,
                query=params,
                success_codes=[200],
                error_codes=None,
                accept="text/plain",
            )
        )

    async def post_archive_export(
        self, *, request: ExportOptions
    ) -> ExportResult | ExportProgress:
        """Export the filesystem changes to a presigned URL"""
        return await self._do_json_with_status(
            {200: ExportResult, 202: ExportProgress},
            _ApiRequest(
                method="POST",
                path_fmt="/archive/export",
                path_args=[],
                body=request,
                query=None,
                success_codes=[200, 202],
                error_codes={
                    400: "ErrorResponse",
                    409: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def post_archive_resume(self) -> QuiesceStatus:
        """Lift the archive freeze"""
        return await self._do_json(
            QuiesceStatus,
            _ApiRequest(
                method="POST",
                path_fmt="/archive/resume",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={409: "ErrorResponse", 500: "ErrorResponse"},
            ),
        )

    async def post_drives_mount(
        self, *, request: DriveMountRequest
    ) -> DriveMountResponse:
        """Attach a drive to a local path"""
        return await self._do_json(
            DriveMountResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/drives/mount",
                path_args=[],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    403: "ErrorResponse",
                    409: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def post_environment_reload(self) -> HandlerReloadResponse:
        """Reload environment from guest metadata"""
        return await self._do_json(
            HandlerReloadResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/environment/reload",
                path_args=[],
                body=None,
                query=None,
                success_codes=[200],
                error_codes={404: "ErrorResponse", 500: "ErrorResponse"},
            ),
        )

    async def post_filesystem_multipart_complete(
        self, *, upload_id: str, request: MultipartCompleteRequest
    ) -> SuccessResponse:
        """Complete multipart upload"""
        return await self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/filesystem-multipart/{}/complete",
                path_args=[upload_id],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    404: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def post_filesystem_multipart_initiate(
        self, *, path: str, request: MultipartInitiateRequest
    ) -> MultipartInitiateResponse:
        """Initiate multipart upload"""
        return await self._do_json(
            MultipartInitiateResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/filesystem-multipart/initiate/{}",
                path_args=[path],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={400: "ErrorResponse", 500: "ErrorResponse"},
            ),
        )

    async def post_network_process_monitor(
        self, *, pid: str, request: PortMonitorRequest
    ) -> PostNetworkProcessMonitorResponse:
        """Start monitoring ports for a process"""
        return await self._do_json(
            PostNetworkProcessMonitorResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/network/process/{}/monitor",
                path_args=[pid],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def post_process(self, *, request: ProcessRequest) -> ProcessResponse:
        """Execute a command"""
        return await self._do_json(
            ProcessResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/process",
                path_args=[],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def post_process_raw(
        self,
        *,
        request: ProcessRequest,
        accept: Literal["application/json", "text/event-stream"],
    ) -> httpx.Response:
        """Execute a command. Returns the response unread, in the requested content type. The caller must close the response."""
        return await self._do_raw(
            _ApiRequest(
                method="POST",
                path_fmt="/process",
                path_args=[],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
                accept=accept,
            )
        )

    async def post_process_stdin(
        self, *, identifier: str, content: bytes | str
    ) -> SuccessResponse:
        """Write to a process's stdin"""
        return await self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/process/{}/stdin",
                path_args=[identifier],
                body=content,
                query=None,
                success_codes=[200],
                error_codes={
                    404: "ErrorResponse",
                    409: "ErrorResponse",
                    413: "ErrorResponse",
                    500: "ErrorResponse",
                    503: "ErrorResponse",
                },
                body_content_type="application/octet-stream",
            ),
        )

    async def post_upgrade(self, *, request: UpgradeRequest) -> SuccessResponse:
        """Upgrade the sandbox-api"""
        return await self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="POST",
                path_fmt="/upgrade",
                path_args=[],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={500: "ErrorResponse"},
            ),
        )

    async def put_codegen_fastapply(
        self, *, path: str, request: ApplyEditRequest
    ) -> ApplyEditResponse:
        """Apply code edit"""
        return await self._do_json(
            ApplyEditResponse,
            _ApiRequest(
                method="PUT",
                path_fmt="/codegen/fastapply/{}",
                path_args=[path],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    503: "ErrorResponse",
                },
            ),
        )

    async def put_filesystem(
        self, *, path: str, request: FileRequest
    ) -> SuccessResponse:
        """Create or update a file or directory"""
        return await self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="PUT",
                path_fmt="/filesystem/{}",
                path_args=[path],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def put_filesystem_multipart_part(
        self, *, upload_id: str, params: PutFilesystemMultipartPartParams, files: Any
    ) -> MultipartUploadPartResponse:
        """Upload part. *files* is sent as httpx ``files``."""
        return await self._do_json(
            MultipartUploadPartResponse,
            _ApiRequest(
                method="PUT",
                path_fmt="/filesystem-multipart/{}/part",
                path_args=[upload_id],
                body=files,
                query=params,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    404: "ErrorResponse",
                    500: "ErrorResponse",
                },
                body_content_type="multipart/form-data",
            ),
        )

    async def put_filesystem_tree(
        self, *, path: str, request: TreeRequest
    ) -> PutFilesystemTreeResponse:
        """Create or update directory tree"""
        return await self._do_json(
            PutFilesystemTreeResponse,
            _ApiRequest(
                method="PUT",
                path_fmt="/filesystem/tree/{}",
                path_args=[path],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    async def put_network_tunnel_config(
        self, *, request: TunnelConfigRequest
    ) -> SuccessResponse:
        """Update tunnel configuration"""
        return await self._do_json(
            SuccessResponse,
            _ApiRequest(
                method="PUT",
                path_fmt="/network/tunnel/config",
                path_args=[],
                body=request,
                query=None,
                success_codes=[200],
                error_codes={
                    400: "ErrorResponse",
                    422: "ErrorResponse",
                    500: "ErrorResponse",
                },
            ),
        )

    def _build_request(self, request: _ApiRequest) -> httpx.Request:
        path = request.path_fmt.format(
            *[urllib.parse.quote(a, safe="") for a in request.path_args]
        )
        json_body = None
        content_body = None
        files_body = None
        headers: dict[str, str] = {}
        if request.accept is not None:
            headers["Accept"] = request.accept
        if request.body is not None:
            if request.body_content_type is None:
                if isinstance(request.body, BaseModel):
                    # Only fields the caller set are sent, so unset fields fall
                    # back to the server default rather than being reset here.
                    # An explicit None is kept, since null can mean "clear".
                    # by_alias: a field renamed for Python (e.g. async_ for
                    # "async") must serialize under its API name.
                    json_body = request.body.model_dump(
                        mode="json", exclude_unset=True, by_alias=True
                    )
                else:
                    json_body = request.body
            elif request.body_content_type == "multipart/form-data":
                # httpx derives the multipart Content-Type, boundary included.
                files_body = request.body
            else:
                headers["Content-Type"] = request.body_content_type
                content_body = request.body
        params = None
        if request.query is not None:
            if isinstance(request.query, BaseModel):
                # As above, plus dropping None: a null query parameter is
                # meaningless and would otherwise serialize as an empty string.
                params = request.query.model_dump(
                    mode="json", exclude_unset=True, exclude_none=True, by_alias=True
                )
            else:
                params = request.query
        return self._http_client.build_request(
            request.method,
            path,
            json=json_body,
            content=content_body,
            files=files_body,
            params=params,
            headers=headers,
        )

    async def _do(self, request: _ApiRequest) -> httpx.Response:
        response = await self._http_client.send(self._build_request(request))
        if response.status_code not in request.success_codes:
            if request.error_codes and response.status_code in request.error_codes:
                error_name = request.error_codes[response.status_code]
                if error_name in _ERROR_TYPES:
                    model_cls, exc_cls, field_name = _ERROR_TYPES[error_name]
                    # A body that does not match the declared error schema
                    # falls through to the generic ResponseError below.
                    model = None
                    with contextlib.suppress(ValidationError):
                        model = model_cls.model_validate_json(response.content)
                    if model is not None:
                        raise exc_cls(
                            status_code=response.status_code,  # ty: ignore[unknown-argument]
                            **{field_name: model},
                        )
            raise ResponseError(status_code=response.status_code, body=response.text)
        return response

    async def _do_raw(self, request: _ApiRequest) -> httpx.Response:
        response = await self._http_client.send(
            self._build_request(request), stream=True
        )
        if response.status_code not in request.success_codes:
            await response.aread()
            if request.error_codes and response.status_code in request.error_codes:
                error_name = request.error_codes[response.status_code]
                if error_name in _ERROR_TYPES:
                    model_cls, exc_cls, field_name = _ERROR_TYPES[error_name]
                    # A body that does not match the declared error schema
                    # falls through to the generic ResponseError below.
                    model = None
                    with contextlib.suppress(ValidationError):
                        model = model_cls.model_validate_json(response.content)
                    if model is not None:
                        raise exc_cls(
                            status_code=response.status_code,  # ty: ignore[unknown-argument]
                            **{field_name: model},
                        )
            raise ResponseError(status_code=response.status_code, body=response.text)
        return response

    async def _do_json(self, response_type: type[_T], request: _ApiRequest) -> _T:
        response = await self._do(request)
        content_type = response.headers.get("content-type", "")
        if not content_type.startswith("application/json"):
            raise ValueError(
                f"unexpected content type {content_type!r}, expected application/json"
            )
        return response_type.model_validate_json(response.content)

    async def _do_json_with_status(
        self, response_types: Mapping[int, type[_T]], request: _ApiRequest
    ) -> _T:
        response = await self._do(request)
        response_type = response_types.get(response.status_code)
        if response_type is None:
            # A bodyless success code, such as 204 alongside a JSON 200. The
            # call site's return type includes None only when one is declared,
            # so this cast is unreachable otherwise.
            return cast(_T, None)
        content_type = response.headers.get("content-type", "")
        if not content_type.startswith("application/json"):
            raise ValueError(
                f"unexpected content type {content_type!r}, expected application/json"
            )
        return response_type.model_validate_json(response.content)
