# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ApplyEditRequest(BaseModel):
    codeEdit: Annotated[
        str,
        Field(
            examples=[
                "// Add world parameter\nfunction hello(world) {\n  console.log('Hello', world);\n}"
            ]
        ),
    ]
    model: Annotated[str | None, Field(examples=["relace-apply-3"])] = None


class ApplyEditResponse(BaseModel):
    message: Annotated[
        str | None, Field(examples=["Code edit applied successfully"])
    ] = None
    originalContent: Annotated[
        str | None, Field(examples=["function hello() {\n  console.log('Hello');\n}"])
    ] = None
    path: Annotated[str | None, Field(examples=["src/main.js"])] = None
    provider: Annotated[str | None, Field(examples=["Relace"])] = None
    success: Annotated[bool | None, Field(examples=[True])] = None
    updatedContent: Annotated[
        str | None,
        Field(examples=["function hello(world) {\n  console.log('Hello', world);\n}"]),
    ] = None


class ArchiveManifest(BaseModel):
    added: Annotated[
        int | None,
        Field(
            description="Added and Modified count the archive's payload members.",
            examples=[11],
        ),
    ] = None
    apiVersion: Annotated[
        str | None,
        Field(
            description="APIVersion is the sandbox-api build that produced the archive.",
            examples=["v0.1.0"],
        ),
    ] = None
    createdAt: str
    deleted: Annotated[
        list[str] | None,
        Field(
            description="Deleted are paths the image has and the sandbox deleted. Tar cannot carry\na deletion, so import applies these from the manifest."
        ),
    ] = None
    excludes: Annotated[
        list[str] | None,
        Field(description="Excludes are the paths left out of the comparison."),
    ] = None
    imageDevice: Annotated[
        str | None,
        Field(
            description="ImageDevice is the device the pristine image was read from, for the record:\nit says where the sandbox that exported the archive found its image.",
            examples=["/dev/vda"],
        ),
    ] = None
    modified: Annotated[int | None, Field(examples=[3])] = None
    payloadBytes: Annotated[
        int | None,
        Field(
            description="PayloadBytes is the total content size of the payload members.",
            examples=[3073449],
        ),
    ] = None
    processes: Annotated[
        bool | None,
        Field(
            description="Processes tells whether ProcessesName is present.",
            examples=[True],
        ),
    ] = None
    root: Annotated[
        str,
        Field(
            description="Root is the directory the paths are relative to.",
            examples=["/"],
        ),
    ]
    version: Annotated[int, Field(examples=[1])]


class ContentSearchMatch(BaseModel):
    column: Annotated[int, Field(examples=[10])]
    context: Annotated[
        str | None, Field(examples=["previous line\ncurrent line\nnext line"])
    ] = None
    line: Annotated[int, Field(examples=[42])]
    path: Annotated[str, Field(examples=["src/main.go"])]
    text: Annotated[str, Field(examples=["const searchText = 'example'"])]


class ContentSearchResponse(BaseModel):
    matches: list[ContentSearchMatch]
    query: Annotated[str, Field(examples=["searchText"])]
    total: Annotated[int, Field(examples=[5])]


class DriveMountInfo(BaseModel):
    driveName: str | None = None
    drivePath: str | None = None
    gidMap: Annotated[
        str | None, Field(description="The local GID used for this mount")
    ] = None
    mountPath: str | None = None
    readOnly: bool | None = None
    uidMap: Annotated[
        str | None, Field(description="The local UID used for this mount")
    ] = None


class DriveMountRequest(BaseModel):
    driveName: str
    drivePath: Annotated[str | None, Field(description='Optional, defaults to "/"')] = (
        None
    )
    gidMap: Annotated[
        str | None,
        Field(description="Optional, local GID to map (filer GID is always 0)"),
    ] = None
    mountPath: str
    readOnly: Annotated[
        bool | None, Field(description="Optional, defaults to false")
    ] = None
    uidMap: Annotated[
        str | None,
        Field(description="Optional, local UID to map (filer UID is always 0)"),
    ] = None


class DriveMountResponse(BaseModel):
    driveName: str | None = None
    drivePath: str | None = None
    gidMap: Annotated[
        str | None, Field(description="The local GID used for this mount")
    ] = None
    message: str | None = None
    mountPath: str | None = None
    readOnly: bool | None = None
    success: bool | None = None
    uidMap: Annotated[
        str | None, Field(description="The local UID used for this mount")
    ] = None


class DriveUnmountResponse(BaseModel):
    message: str | None = None
    mountPath: str | None = None
    success: bool | None = None


class ErrorResponse(BaseModel):
    error: Annotated[str, Field(examples=["Error message"])]


class File(BaseModel):
    group: str
    lastModified: str
    name: str
    owner: str
    path: str
    permissions: str
    size: int


class FileRequest(BaseModel):
    content: Annotated[str | None, Field(examples=["file contents here"])] = None
    isDirectory: Annotated[bool | None, Field(examples=[False])] = None
    permissions: Annotated[str | None, Field(examples=["0644"])] = None


class FileWithContent(BaseModel):
    content: str
    group: str
    lastModified: str
    name: str
    owner: str
    path: str
    permissions: str
    size: int


class FindMatch(BaseModel):
    path: Annotated[str, Field(examples=["src/main.go"])]
    type: Annotated[str, Field(description='"file" or "directory"', examples=["file"])]


class FindResponse(BaseModel):
    matches: list[FindMatch]
    total: Annotated[int, Field(examples=[5])]


class FuzzySearchMatch(BaseModel):
    path: Annotated[str, Field(examples=["src/main.go"])]
    score: Annotated[int, Field(examples=[100])]
    type: Annotated[str, Field(description='"file" or "directory"', examples=["file"])]


class FuzzySearchResponse(BaseModel):
    matches: list[FuzzySearchMatch]
    total: Annotated[int, Field(examples=[5])]


class MultipartInitiateRequest(BaseModel):
    permissions: Annotated[str | None, Field(examples=["0644"])] = None


class MultipartInitiateResponse(BaseModel):
    path: Annotated[str | None, Field(examples=["/tmp/largefile.dat"])] = None
    uploadId: Annotated[
        str | None, Field(examples=["550e8400-e29b-41d4-a716-446655440000"])
    ] = None


class MultipartPartInfo(BaseModel):
    etag: Annotated[
        str | None, Field(examples=["5d41402abc4b2a76b9719d911017c592"])
    ] = None
    partNumber: Annotated[int | None, Field(examples=[1])] = None


class MultipartUpload(BaseModel):
    abortUrl: Annotated[
        str | None,
        Field(
            description="AbortURL is a presigned DELETE URL that discards the parts already\nuploaded. Without it a failed export leaves them on the storage until a\nlifecycle rule removes them."
        ),
    ] = None
    completeUrl: Annotated[
        str | None,
        Field(
            description="CompleteURL is a presigned POST URL that assembles the parts."
        ),
    ] = None
    partSize: Annotated[
        int | None,
        Field(
            description="PartSize is the number of bytes sent to every part but the last.",
            examples=[536870912],
        ),
    ] = None
    partUrls: Annotated[
        list[str] | None,
        Field(
            description="PartURLs are presigned PUT URLs, one per part, in order. Extra ones are\nleft unused."
        ),
    ] = None


class MultipartUploadPartResponse(BaseModel):
    etag: Annotated[
        str | None, Field(examples=["5d41402abc4b2a76b9719d911017c592"])
    ] = None
    partNumber: Annotated[int | None, Field(examples=[1])] = None
    size: Annotated[int | None, Field(examples=[5242880])] = None


class PortMonitorRequest(BaseModel):
    callback: Annotated[
        str | None,
        Field(
            description="URL to call when a new port is detected",
            examples=["http://localhost:3000/callback"],
        ),
    ] = None


class ProcessLogs(BaseModel):
    logs: Annotated[str, Field(examples=["logs output"])]
    stderr: Annotated[str, Field(examples=["stderr output"])]
    stdout: Annotated[str, Field(examples=["stdout output"])]


class ProcessRequest(BaseModel):
    command: Annotated[str, Field(examples=["ls -la"])]
    env: Annotated[dict[str, str] | None, Field(examples=[{'{"PORT"': ' "3000"}'}])] = (
        None
    )
    keepAlive: Annotated[
        bool | None,
        Field(
            description="Disable scale-to-zero while process runs. Default timeout is 600s (10 minutes). Set timeout to 0 for infinite.",
            examples=[False],
        ),
    ] = None
    maxRestarts: Annotated[
        int | None,
        Field(
            description="Maximum number of restarts on failure. Set to a negative value (e.g. -1) for unlimited restarts.",
            examples=[3],
        ),
    ] = None
    name: Annotated[str | None, Field(examples=["my-process"])] = None
    restartOnFailure: Annotated[bool | None, Field(examples=[True])] = None
    stdin: Annotated[
        bool | None,
        Field(
            description="Open a writable stdin pipe, fed via POST /process/{identifier}/stdin and closed via DELETE. The pipe does not survive a sandbox-api restart: the process then sees EOF.",
            examples=[False],
        ),
    ] = None
    timeout: Annotated[
        int | None,
        Field(
            description="Timeout in seconds. When keepAlive is true, defaults to 600s (10 minutes). Set to 0 for infinite (no auto-kill).",
            examples=[30],
        ),
    ] = None
    waitForCompletion: Annotated[bool | None, Field(examples=[False])] = None
    waitForPorts: Annotated[list[int] | None, Field(examples=[[3000, 8080]])] = None
    workingDir: Annotated[str | None, Field(examples=["/home/user"])] = None


class Status(StrEnum):
    failed = "failed"
    killed = "killed"
    stopped = "stopped"
    running = "running"
    completed = "completed"


class ProcessResponse(BaseModel):
    command: Annotated[str, Field(examples=["ls -la"])]
    completedAt: Annotated[str, Field(examples=["Wed, 01 Jan 2023 12:01:00 GMT"])]
    exitCode: Annotated[int, Field(examples=[0])]
    keepAlive: Annotated[
        bool | None,
        Field(
            description="Whether scale-to-zero is disabled for this process",
            examples=[False],
        ),
    ] = None
    logs: Annotated[str, Field(examples=["logs output"])]
    maxRestarts: Annotated[int | None, Field(examples=[3])] = None
    name: Annotated[str, Field(examples=["my-process"])]
    pid: Annotated[str, Field(examples=["1234"])]
    restartCount: Annotated[int | None, Field(examples=[2])] = None
    restartOnFailure: Annotated[bool | None, Field(examples=[True])] = None
    startedAt: Annotated[str, Field(examples=["Wed, 01 Jan 2023 12:00:00 GMT"])]
    status: Annotated[Status, Field(examples=["running"])]
    stderr: Annotated[str, Field(examples=["stderr output"])]
    stdin: Annotated[
        bool | None,
        Field(
            description="Whether the process was started with a writable stdin pipe",
            examples=[False],
        ),
    ] = None
    stdout: Annotated[str, Field(examples=["stdout output"])]
    workingDir: Annotated[str, Field(examples=["/home/user"])]


class RankedFile(BaseModel):
    content: str | None = None
    path: str | None = None
    score: float | None = None


class RerankingResponse(BaseModel):
    files: list[RankedFile] | None = None
    message: Annotated[str | None, Field(examples=["Found 5 relevant files"])] = None
    success: Annotated[bool | None, Field(examples=[True])] = None


class Subdirectory(BaseModel):
    name: str
    path: str


class SuccessResponse(BaseModel):
    message: Annotated[str, Field(examples=["File created successfully"])]
    path: Annotated[str | None, Field(examples=["/path/to/file"])] = None


class TreeRequest(BaseModel):
    files: Annotated[
        dict[str, str] | None,
        Field(
            examples=[{'"dir/file2.txt"': '"content2"}', '{"file1.txt"': '"content1"'}]
        ),
    ] = None


class TunnelConfigRequest(BaseModel):
    config: Annotated[
        str,
        Field(
            description="Base64-encoded tunnel config JSON",
            examples=["eyJsb2NhbF9pcCI6ICIxMC4wLjAuMS8zMiIsIC4uLn0="],
        ),
    ]


class UpgradeRequest(BaseModel):
    baseUrl: Annotated[
        str | None,
        Field(
            description="Base URL for releases (useful for forks)",
            examples=["https://github.com/blaxel-ai/sandbox/releases"],
        ),
    ] = None
    version: Annotated[
        str | None,
        Field(
            description='Version to upgrade to: "latest" (default), "develop", "main", or specific tag like "v1.0.0"',
            examples=["latest"],
        ),
    ] = None


class GetCodegenRerankingParams(BaseModel):
    query: Annotated[str, Field(description="Natural language query to search for")]
    scoreThreshold: Annotated[
        float | None, Field(description="Minimum relevance score (default: 0.5)")
    ] = None
    tokenLimit: Annotated[
        int | None, Field(description="Maximum tokens to return (default: 30000)")
    ] = None
    filePattern: Annotated[
        str | None,
        Field(
            description="Regex pattern to filter files (e.g., .*\\\\.ts$ for TypeScript files)"
        ),
    ] = None


class GetFilesystemContentSearchParams(BaseModel):
    query: Annotated[str, Field(description="Text to search for")]
    caseSensitive: Annotated[
        bool | None, Field(description="Case sensitive search (default: false)")
    ] = None
    maxResults: Annotated[
        int | None,
        Field(description="Maximum number of results to return (default: 100)"),
    ] = None
    filePattern: Annotated[
        str | None, Field(description="File pattern to include (e.g., *.go)")
    ] = None
    excludeDirs: Annotated[
        str | None,
        Field(
            description="Comma-separated directory names to skip (default: node_modules,vendor,.git,dist,build,target,__pycache__,.venv,.next,coverage)"
        ),
    ] = None


class GetFilesystemFindParams(BaseModel):
    type: Annotated[
        str | None, Field(description="Type of search (file or directory)")
    ] = None
    patterns: Annotated[
        str | None,
        Field(description="Comma-separated file patterns to include (e.g., *.go,*.js)"),
    ] = None
    maxResults: Annotated[
        int | None,
        Field(
            description="Maximum number of results to return (default: 20). If set to 0, all results will be returned."
        ),
    ] = None
    excludeDirs: Annotated[
        str | None,
        Field(
            description="Comma-separated directory names to skip (default: node_modules,vendor,.git,dist,build,target,__pycache__,.venv,.next,coverage). Use empty string to skip no directories."
        ),
    ] = None
    excludeHidden: Annotated[
        bool | None,
        Field(description="Exclude hidden files and directories (default: true)"),
    ] = None


class PutFilesystemMultipartPartParams(BaseModel):
    partNumber: Annotated[int, Field(description="Part number (1-10000)")]


class GetFilesystemSearchParams(BaseModel):
    maxResults: Annotated[
        int | None,
        Field(description="Maximum number of results to return (default: 20)"),
    ] = None
    patterns: Annotated[
        str | None,
        Field(description="Comma-separated file patterns to include (e.g., *.go,*.js)"),
    ] = None
    excludeDirs: Annotated[
        str | None,
        Field(
            description="Comma-separated directory names to skip (default: node_modules,vendor,.git,dist,build,target,__pycache__,.venv,.next,coverage). Use empty string to skip no directories."
        ),
    ] = None
    excludeHidden: Annotated[
        bool | None,
        Field(description="Exclude hidden files and directories (default: true)"),
    ] = None


class DeleteFilesystemParams(BaseModel):
    recursive: Annotated[
        bool | None, Field(description="Delete directory recursively")
    ] = None


class GetFilesystemParams(BaseModel):
    download: Annotated[
        bool | None, Field(description="Force download mode for files")
    ] = None


class DeleteFilesystemTreeParams(BaseModel):
    recursive: Annotated[
        bool | None, Field(description="Delete directory recursively")
    ] = None


class GetWatchFilesystemParams(BaseModel):
    ignore: Annotated[
        str | None, Field(description="Ignore patterns (comma-separated)")
    ] = None


class DeleteNetworkProcessMonitorResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class PostNetworkProcessMonitorResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class GetNetworkProcessPortsResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class GetProcessResponse(RootModel[list[ProcessResponse]]):
    root: list[ProcessResponse]


class ArchiveChangeKind(StrEnum):
    ChangeAdded = "added"
    ChangeModified = "modified"
    ChangeDeleted = "deleted"


class ArchiveExportState(StrEnum):
    ExportRunning = "running"
    ExportSucceeded = "succeeded"
    ExportFailed = "failed"


class ArchiveQuiesceState(StrEnum):
    StateActive = "active"
    StateQuiescing = "quiescing"
    StateQuiesced = "quiesced"
    StateRestoring = "restoring"


class ArchiveRestoreState(StrEnum):
    RestoreDownloading = "downloading"
    RestoreExtracting = "extracting"
    RestoreRelaunching = "relaunching"
    RestoreSucceeded = "succeeded"
    RestoreFailed = "failed"


class FilesystemUploadedPart(BaseModel):
    etag: Annotated[
        str | None, Field(examples=["5d41402abc4b2a76b9719d911017c592"])
    ] = None
    partNumber: Annotated[int | None, Field(examples=[1])] = None
    size: Annotated[int | None, Field(examples=[5242880])] = None
    uploadedAt: str | None = None


class HandlerReloadResponse(BaseModel):
    applied: int | None = None
    generation: int | None = None
    removed: int | None = None


class ProcessUpgradeState(StrEnum):
    UpgradeStateIdle = "idle"
    UpgradeStateRunning = "running"
    UpgradeStateCompleted = "completed"
    UpgradeStateFailed = "failed"


class Directory(BaseModel):
    files: list[File]
    name: str
    path: str
    subdirectories: Annotated[
        list[Subdirectory], Field(description="@name Subdirectories")
    ]


class DriveListResponse(BaseModel):
    mounts: list[DriveMountInfo] | None = None


class ExportOptions(BaseModel):
    async_: Annotated[
        bool | None,
        Field(
            alias="async",
            description="Async starts the export and answers immediately, leaving it to run: an\narchive of a large filesystem takes longer than a request may be held\nopen. Its progress is reported by /archive/status.",
            examples=[False],
        ),
    ] = None
    dryRun: Annotated[
        bool | None,
        Field(
            description="DryRun reports what would be archived, and its exact size, without\nstopping anything and without uploading.",
            examples=[False],
        ),
    ] = None
    excludes: Annotated[
        list[str] | None,
        Field(description="Excludes are added to the paths excluded by default."),
    ] = None
    headers: Annotated[
        dict[str, str] | None,
        Field(
            description="Headers are sent with the upload request as given. A presigned URL only\naccepts the headers it was signed for, so these have to match what the\ncaller signed: sending one that was not signed, or signing one that is not\nsent, is rejected as a signature mismatch. Typical use is a storage class,\nx-amz-storage-class: GLACIER_IR."
        ),
    ] = None
    imageDevice: Annotated[
        str | None,
        Field(
            description="ImageDevice is the device holding the pristine image. It is found on its\nown, wherever the sandbox booted from attached it, and naming one here\nonly overrides that.",
            examples=["/dev/vda"],
        ),
    ] = None
    imageMountPoint: Annotated[
        str | None,
        Field(
            description="ImageMountPoint is a directory where the pristine image is already mounted.\nWhen set the image device is neither mounted nor unmounted.",
            examples=["/mnt/lower"],
        ),
    ] = None
    multipart: Annotated[
        MultipartUpload | None,
        Field(
            description="Multipart uploads the archive part by part instead, which is how an\narchive larger than the 5 GB a single PUT accepts is stored. It takes\nprecedence over URL."
        ),
    ] = None
    saveProcesses: Annotated[
        bool | None,
        Field(
            description="SaveProcesses stores the process list in the archive so restore can\nrelaunch the workload. Defaults to true; set it to false to archive\nstorage only.",
            examples=[True],
        ),
    ] = None
    stopTimeoutSeconds: Annotated[
        int | None,
        Field(
            description="StopTimeoutSeconds bounds the graceful stop of each process.",
            examples=[30],
        ),
    ] = None
    url: Annotated[
        str | None,
        Field(
            description="URL is a presigned S3 PUT URL the archive is streamed to. Empty is only\nvalid with DryRun, or with Multipart.",
            examples=["https://bucket.s3.amazonaws.com/key?..."],
        ),
    ] = None


class ExportProgress(BaseModel):
    error: Annotated[
        str | None,
        Field(
            description="Error is why the export failed, without the presigned URL it used."
        ),
    ] = None
    finishedAt: str | None = None
    size: Annotated[
        int | None,
        Field(
            description="Size is the archive's exact size, known once the filesystem is scanned.",
            examples=[3074211],
        ),
    ] = None
    startedAt: str | None = None
    state: Annotated[ArchiveExportState | None, Field(examples=["running"])] = None
    uploaded: Annotated[
        bool | None,
        Field(
            description="Uploaded reports whether the storage holds the archive.",
            examples=[False],
        ),
    ] = None


class MultipartCompleteRequest(BaseModel):
    parts: list[MultipartPartInfo] | None = None


class MultipartListPartsResponse(BaseModel):
    parts: list[FilesystemUploadedPart] | None = None
    uploadId: Annotated[
        str | None, Field(examples=["550e8400-e29b-41d4-a716-446655440000"])
    ] = None


class RestoreProgress(BaseModel):
    deleted: Annotated[int | None, Field(examples=[3])] = None
    downloaded: Annotated[
        int | None,
        Field(
            description="Downloaded is how much of the archive has been read so far.",
            examples=[1048576],
        ),
    ] = None
    error: Annotated[
        str | None,
        Field(
            description="Error is why the restore failed, without the presigned URL it used."
        ),
    ] = None
    finishedAt: str | None = None
    restored: Annotated[
        int | None,
        Field(
            description="Restored and Deleted count what the archive changed on the filesystem.",
            examples=[1204],
        ),
    ] = None
    size: Annotated[
        int | None,
        Field(
            description="Size is the archive's size as the storage announced it, and zero when it\nannounced none - a client showing a percentage has to allow for that.",
            examples=[3074211],
        ),
    ] = None
    startedAt: str | None = None
    state: Annotated[ArchiveRestoreState | None, Field(examples=["extracting"])] = None


class UpgradeStatus(BaseModel):
    binaryPath: Annotated[
        str | None,
        Field(
            description="Path to downloaded binary", examples=["/tmp/sandbox-api-new"]
        ),
    ] = None
    bytesDownloaded: Annotated[
        int | None, Field(description="Bytes downloaded", examples=[25034936])
    ] = None
    downloadUrl: Annotated[
        str | None,
        Field(description="URL used for download", examples=["https://github.com/..."]),
    ] = None
    error: Annotated[
        str | None,
        Field(
            description="Error message if failed",
            examples=["Failed to download binary"],
        ),
    ] = None
    lastAttempt: Annotated[
        str | None, Field(description="When the upgrade was attempted")
    ] = None
    status: Annotated[
        ProcessUpgradeState,
        Field(
            description="Current state (idle, running, completed, failed)",
            examples=["running"],
        ),
    ]
    step: Annotated[
        str,
        Field(
            description="Current/last step (none, starting, download, validate, replace, completed, skipped)",
            examples=["download"],
        ),
    ]
    version: Annotated[
        str, Field(description="Version being upgraded to", examples=["latest"])
    ]


class GetFilesystemResponse(RootModel[Directory | FileWithContent | bytes]):
    root: Directory | FileWithContent | bytes


class GetFilesystemTreeResponse(RootModel[Directory | FileWithContent | bytes]):
    root: Directory | FileWithContent | bytes


class PutFilesystemTreeResponse(RootModel[Directory | FileWithContent | bytes]):
    root: Directory | FileWithContent | bytes


class ArchiveChange(BaseModel):
    kind: Annotated[ArchiveChangeKind, Field(examples=["added"])]
    path: Annotated[
        str,
        Field(
            description="Path is relative to the root, without a leading slash.",
            examples=["usr/bin/curl"],
        ),
    ]
    size: Annotated[
        int | None,
        Field(
            description="Size is the file content size in bytes, 0 for anything but a regular file.",
            examples=[256216],
        ),
    ] = None


class FilesystemMultipartUpload(BaseModel):
    initiatedAt: str | None = None
    parts: dict[str, FilesystemUploadedPart] | None = None
    path: Annotated[str | None, Field(examples=["/tmp/largefile.dat"])] = None
    permissions: Annotated[int | None, Field(examples=[420])] = None
    uploadId: Annotated[
        str | None, Field(examples=["550e8400-e29b-41d4-a716-446655440000"])
    ] = None


class ExportResult(BaseModel):
    changes: Annotated[
        list[ArchiveChange] | None,
        Field(
            description="Changes lists every path in the archive. Only filled for a dry run,\nwhere it is the point of the call."
        ),
    ] = None
    duration: Annotated[str | None, Field(examples=["4.2s"])] = None
    manifest: ArchiveManifest
    size: Annotated[
        int | None,
        Field(
            description="Size is the exact number of bytes uploaded, known before the upload\nstarts since the archive is not compressed.",
            examples=[3074211],
        ),
    ] = None
    stoppedProcesses: Annotated[
        list[str] | None,
        Field(
            description="StoppedProcesses are the processes stopped to freeze the filesystem."
        ),
    ] = None
    uploaded: Annotated[
        bool | None,
        Field(description="Uploaded is false for a dry run.", examples=[True]),
    ] = None


class HealthResponse(BaseModel):
    arch: Annotated[str, Field(examples=["amd64"])]
    buildTime: Annotated[str, Field(examples=["2026-01-29T17:36:52+00:00"])]
    gitCommit: Annotated[str, Field(examples=["abc123"])]
    goVersion: Annotated[str, Field(examples=["go1.25.0"])]
    lastUpgrade: UpgradeStatus
    os: Annotated[str, Field(examples=["linux"])]
    startedAt: Annotated[str, Field(examples=["2026-01-29T18:45:49+00:00"])]
    status: Annotated[str, Field(examples=["ok"])]
    upgradeCount: Annotated[int, Field(examples=[0])]
    uptime: Annotated[str, Field(examples=["1h30m"])]
    uptimeSeconds: Annotated[float, Field(examples=[5400.5])]
    version: Annotated[str, Field(examples=["v0.1.0"])]


class MultipartListUploadsResponse(BaseModel):
    uploads: list[FilesystemMultipartUpload] | None = None


class QuiesceStatus(BaseModel):
    export: Annotated[
        ExportProgress | None,
        Field(
            description="Export reports the export started asynchronously, if there was one. It is\nhow a caller that did not wait for the export learns that the archive is\non the storage, or why it is not."
        ),
    ] = None
    readOnlyRoot: Annotated[
        bool | None,
        Field(
            description="ReadOnlyRoot reports whether the root mount was remounted read-only, which\nis what actually stops writes; false means the freeze relies only on the\nAPI refusing calls, and the reason says why.",
            examples=[True],
        ),
    ] = None
    reason: Annotated[
        str | None,
        Field(
            description="Reason is a human readable explanation of why the sandbox is frozen.",
            examples=["archive export"],
        ),
    ] = None
    restore: Annotated[
        RestoreProgress | None,
        Field(
            description="Restore reports the archive this sandbox was started from, if it was\nstarted from one: how far its restore has got, and how it ended."
        ),
    ] = None
    since: Annotated[
        str | None, Field(description="Since is when the sandbox left StateActive.")
    ] = None
    state: Annotated[ArchiveQuiesceState, Field(examples=["quiesced"])]
    stoppedProcesses: Annotated[
        list[str] | None,
        Field(
            description="StoppedProcesses are the process identifiers stopped while quiescing."
        ),
    ] = None
