"""Code generator for Baseten Python SDK.

Usage:
    python -m scripts.apigen
    python -m scripts.apigen --update-specs
"""

import argparse
import ast
import subprocess
import sys
import urllib.request
from pathlib import Path

from scripts.apigen.clientgen import generate_client
from scripts.apigen.postprocess import postprocess_models
from scripts.apigen.preprocess import preprocess_spec, preprocess_truss_config_schema

MANAGEMENT_SPEC_URL = "https://api.baseten.co/v1/spec"
INFERENCE_SPEC_URL = "https://api.baseten.co/inference-spec"
TRUSS_CONFIG_SCHEMA_URL = (
    "https://raw.githubusercontent.com/basetenlabs/truss/main/truss/config.schema.json"
)

APIGEN_DIR = Path(__file__).parent
SPECS_DIR = APIGEN_DIR / "specs"
REPO_ROOT = APIGEN_DIR.parent.parent
CLIENT_DIR = REPO_ROOT / "baseten" / "client"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--update-specs",
        action="store_true",
        help="Download latest specs from remote URLs before generating",
    )
    args = parser.parse_args()

    if args.update_specs:
        print("Updating specs from remote URLs...")
        download_spec(MANAGEMENT_SPEC_URL, SPECS_DIR / "management.json")
        download_spec(INFERENCE_SPEC_URL, SPECS_DIR / "inference.json")
        download_spec(TRUSS_CONFIG_SCHEMA_URL, SPECS_DIR / "config.schema.json")

    generate_api(
        SPECS_DIR / "management.json", CLIENT_DIR / "managementapi", "Management"
    )
    generate_api(SPECS_DIR / "inference.json", CLIENT_DIR / "inferenceapi", "Inference")
    generate_modelconfig(SPECS_DIR / "config.schema.json", CLIENT_DIR / "modelconfig")


def download_spec(url: str, dest: Path) -> None:
    print(f"  {url} -> {dest}")
    with urllib.request.urlopen(url) as resp:
        dest.write_bytes(resp.read())


def generate_api(spec_file: Path, out_dir: Path, display_name: str) -> None:
    print(f"Generating {out_dir.name} from {spec_file}")
    out_dir.mkdir(parents=True, exist_ok=True)

    preprocessed = preprocess_spec(spec_file.read_bytes())

    models_file = out_dir / "_models.py"
    run_datamodel_codegen(preprocessed, models_file)
    print(f"  -> {models_file}")

    client_file = out_dir / "_client.py"
    generate_client(preprocessed, client_file)
    print(f"  -> {client_file}")

    init_file = out_dir / "__init__.py"
    generate_init(display_name, models_file, client_file, init_file)
    print(f"  -> {init_file}")

    for f in (models_file, client_file, init_file):
        run_ruff(f)


def generate_modelconfig(spec_file: Path, out_dir: Path) -> None:
    print(f"Generating {out_dir.name} from {spec_file}")
    out_dir.mkdir(parents=True, exist_ok=True)

    preprocessed = preprocess_truss_config_schema(spec_file.read_bytes())

    models_file = out_dir / "_models.py"
    run_datamodel_codegen(preprocessed, models_file, input_file_type="jsonschema")
    models_file.write_text(postprocess_models(models_file.read_text()))
    print(f"  -> {models_file}")

    init_file = out_dir / "__init__.py"
    generate_modelconfig_init(models_file, init_file)
    print(f"  -> {init_file}")

    for f in (models_file, init_file):
        run_ruff(f)


def generate_modelconfig_init(models_file: Path, out_file: Path) -> None:
    model_names = sorted(_public_class_names(models_file))
    model_imports = ", ".join(model_names)
    all_entries = "\n".join(f'    "{name}",' for name in model_names)

    out_file.write_text(f'''\
# Code generated by apigen. DO NOT EDIT.

"""Generated models for the Baseten model config (truss config.yaml).

Types in this module are generated from the Truss config JSON schema and are
NOT covered by any stability or compatibility guarantees. They may change
without notice between versions.
"""

from ._models import {model_imports}

__all__ = [
{all_entries}
]
''')


def generate_init(
    display_name: str, models_file: Path, client_file: Path, out_file: Path
) -> None:
    model_names = _public_class_names(models_file)
    client_names = _public_class_names(client_file)
    all_names = sorted(client_names) + sorted(model_names)

    model_imports = ", ".join(sorted(model_names))
    client_imports = ", ".join(sorted(client_names))

    all_entries = "\n".join(f'    "{name}",' for name in all_names)

    out_file.write_text(f'''\
# Code generated by apigen. DO NOT EDIT.

"""Generated client and models for the Baseten {display_name} API.

Use :class:`ApiClient` for synchronous access or :class:`AsyncApiClient` for
asynchronous access.

Types in this module are generated from the OpenAPI specification and are NOT
covered by any stability or compatibility guarantees. They may change without
notice between versions.
"""

from ._client import {client_imports}
from ._models import {model_imports}

__all__ = [
{all_entries}
]
''')


def _public_class_names(path: Path) -> list[str]:
    tree = ast.parse(path.read_text())
    return [
        node.name
        for node in ast.iter_child_nodes(tree)
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_")
    ]


def run_datamodel_codegen(
    spec_data: bytes, out_file: Path, input_file_type: str = "openapi"
) -> None:
    args = [
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input-file-type",
        input_file_type,
        "--output",
        str(out_file),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.10",
        "--use-annotated",
        "--set-default-enum-member",
        "--disable-timestamp",
        "--formatters",
        "ruff-format",
        "ruff-check",
    ]
    if input_file_type == "openapi":
        args += ["--openapi-scopes", "schemas"]
    subprocess.run(args, input=spec_data, check=True)


def run_ruff(file: Path) -> None:
    subprocess.run(
        [sys.executable, "-m", "ruff", "format", str(file)],
        check=True,
    )
    subprocess.run(
        [sys.executable, "-m", "ruff", "check", "--fix", str(file)],
        check=True,
    )


if __name__ == "__main__":
    main()
